/**
 * Chart of Accounts Model
 * الشجرة المحاسبية المتكاملة لنظام إدارة الفنادق
 * 
 * This file contains the complete chart of accounts structure
 * for a hotel/property management system following standard accounting principles.
 */

/**
 * Account Type Enum
 * أنواع الحسابات المحاسبية
 */
export enum AccountType {
  ASSET = 'asset',              // الأصول
  LIABILITY = 'liability',      // الخصوم
  EQUITY = 'equity',            // حقوق الملكية
  REVENUE = 'revenue',          // الإيرادات
  EXPENSE = 'expense'           // المصروفات
}

/**
 * Account Nature (Debit/Credit)
 * طبيعة الحساب (مدين/دائن)
 */
export enum AccountNature {
  DEBIT = 'debit',      // مدين (الأصول والمصروفات)
  CREDIT = 'credit'     // دائن (الخصوم وحقوق الملكية والإيرادات)
}

/**
 * Account Status
 * حالة الحساب
 */
export enum AccountStatus {
  ACTIVE = 'active',
  INACTIVE = 'inactive',
  ARCHIVED = 'archived'
}

/**
 * Account Interface
 * واجهة الحساب المحاسبي
 */
export interface Account {
  id: string;                          // رقم الحساب (مثل: 1010, 2010)
  code: string;                         // كود الحساب
  parentId?: string;                    // رقم الحساب الأب (للحسابات الفرعية)
  name: string;                         // اسم الحساب بالعربية
  nameEn: string;                       // اسم الحساب بالإنجليزية
  type: AccountType;                    // نوع الحساب
  nature: AccountNature;                // طبيعة الحساب
  level: number;                        // مستوى الحساب في الشجرة (1, 2, 3...)
  isParent: boolean;                    // هل الحساب أب (يحتوي على حسابات فرعية)
  isActive: boolean;                    // هل الحساب نشط
  status: AccountStatus;               // حالة الحساب
  description?: string;                 // وصف الحساب
  descriptionEn?: string;               // وصف الحساب بالإنجليزية
  notes?: string;                       // ملاحظات الحساب
  taxNumber?: string;                   // الرقم الضريبي
  balance: number;                      // الرصيد الحالي
  openingBalance: number;                // الرصيد الافتتاحي
  currency: string;                     // العملة (SAR, USD, etc.)
  isSystemAccount: boolean;            // هل الحساب نظامي (لا يمكن حذفه)
  allowManualEntry: boolean;           // هل يسمح بإدخال قيود يدوية
  displayOrder: number;                // ترتيب العرض
  tags?: string[];                     // علامات للحساب
  metadata?: Record<string, any>;       // بيانات إضافية
  createdAt?: Date;
  updatedAt?: Date;
  createdBy?: string;
  updatedBy?: string;
}

/**
 * Chart of Accounts Structure
 * هيكل الشجرة المحاسبية
 */
export class ChartOfAccounts {
  /**
   * Get Complete Chart of Accounts
   * الحصول على الشجرة المحاسبية الكاملة
   */
  static getAccounts(): Account[] {
    return [
      // ============================================
      // 1. ASSETS - الأصول (1xxx)
      // ============================================
      
      // 1.1 Current Assets - الأصول المتداولة (11xx)
      {
        id: '1100',
        code: '1100',
        name: 'الأصول المتداولة',
        nameEn: 'Current Assets',
        type: AccountType.ASSET,
        nature: AccountNature.DEBIT,
        level: 1,
        isParent: true,
        isActive: true,
        status: AccountStatus.ACTIVE,
        balance: 0,
        openingBalance: 0,
        currency: 'SAR',
        isSystemAccount: true,
        allowManualEntry: false,
        displayOrder: 1
      },
      {
        id: '1110',
        code: '1110',
        parentId: '1100',
        name: 'النقدية وما في حكمها',
        nameEn: 'Cash and Cash Equivalents',
        type: AccountType.ASSET,
        nature: AccountNature.DEBIT,
        level: 2,
        isParent: true,
        isActive: true,
        status: AccountStatus.ACTIVE,
        balance: 0,
        openingBalance: 0,
        currency: 'SAR',
        isSystemAccount: true,
        allowManualEntry: false,
        displayOrder: 1
      },
      {
        id: '1111',
        code: '1111',
        parentId: '1110',
        name: 'الصندوق الرئيسي',
        nameEn: 'Main Cash',
        type: AccountType.ASSET,
        nature: AccountNature.DEBIT,
        level: 3,
        isParent: false,
        isActive: true,
        status: AccountStatus.ACTIVE,
        balance: 0,
        openingBalance: 0,
        currency: 'SAR',
        isSystemAccount: true,
        allowManualEntry: true,
        displayOrder: 1
      },
      {
        id: '1112',
        code: '1112',
        parentId: '1110',
        name: 'صندوق الاستقبال',
        nameEn: 'Reception Cash',
        type: AccountType.ASSET,
        nature: AccountNature.DEBIT,
        level: 3,
        isParent: false,
        isActive: true,
        status: AccountStatus.ACTIVE,
        balance: 0,
        openingBalance: 0,
        currency: 'SAR',
        isSystemAccount: true,
        allowManualEntry: true,
        displayOrder: 2
      },
      {
        id: '1113',
        code: '1113',
        parentId: '1110',
        name: 'صندوق المطعم',
        nameEn: 'Restaurant Cash',
        type: AccountType.ASSET,
        nature: AccountNature.DEBIT,
        level: 3,
        isParent: false,
        isActive: true,
        status: AccountStatus.ACTIVE,
        balance: 0,
        openingBalance: 0,
        currency: 'SAR',
        isSystemAccount: true,
        allowManualEntry: true,
        displayOrder: 3
      },
      {
        id: '1120',
        code: '1120',
        parentId: '1100',
        name: 'البنوك',
        nameEn: 'Banks',
        type: AccountType.ASSET,
        nature: AccountNature.DEBIT,
        level: 2,
        isParent: true,
        isActive: true,
        status: AccountStatus.ACTIVE,
        balance: 0,
        openingBalance: 0,
        currency: 'SAR',
        isSystemAccount: true,
        allowManualEntry: false,
        displayOrder: 2
      },
      {
        id: '1121',
        code: '1121',
        parentId: '1120',
        name: 'البنك الأهلي - حساب جاري',
        nameEn: 'Al Ahli Bank - Current Account',
        type: AccountType.ASSET,
        nature: AccountNature.DEBIT,
        level: 3,
        isParent: false,
        isActive: true,
        status: AccountStatus.ACTIVE,
        balance: 0,
        openingBalance: 0,
        currency: 'SAR',
        isSystemAccount: false,
        allowManualEntry: true,
        displayOrder: 1
      },
      {
        id: '1122',
        code: '1122',
        parentId: '1120',
        name: 'البنك الأهلي - حساب توفير',
        nameEn: 'Al Ahli Bank - Savings Account',
        type: AccountType.ASSET,
        nature: AccountNature.DEBIT,
        level: 3,
        isParent: false,
        isActive: true,
        status: AccountStatus.ACTIVE,
        balance: 0,
        openingBalance: 0,
        currency: 'SAR',
        isSystemAccount: false,
        allowManualEntry: true,
        displayOrder: 2
      },
      {
        id: '1130',
        code: '1130',
        parentId: '1100',
        name: 'العملاء والمدينون',
        nameEn: 'Accounts Receivable',
        type: AccountType.ASSET,
        nature: AccountNature.DEBIT,
        level: 2,
        isParent: true,
        isActive: true,
        status: AccountStatus.ACTIVE,
        balance: 0,
        openingBalance: 0,
        currency: 'SAR',
        isSystemAccount: true,
        allowManualEntry: false,
        displayOrder: 3
      },
      {
        id: '1131',
        code: '1131',
        parentId: '1130',
        name: 'ذمم عملاء الحجوزات',
        nameEn: 'Booking Receivables',
        type: AccountType.ASSET,
        nature: AccountNature.DEBIT,
        level: 3,
        isParent: false,
        isActive: true,
        status: AccountStatus.ACTIVE,
        balance: 0,
        openingBalance: 0,
        currency: 'SAR',
        isSystemAccount: true,
        allowManualEntry: false,
        displayOrder: 1
      },
      {
        id: '1132',
        code: '1132',
        parentId: '1130',
        name: 'ذمم عملاء B2B',
        nameEn: 'B2B Receivables',
        type: AccountType.ASSET,
        nature: AccountNature.DEBIT,
        level: 3,
        isParent: false,
        isActive: true,
        status: AccountStatus.ACTIVE,
        balance: 0,
        openingBalance: 0,
        currency: 'SAR',
        isSystemAccount: true,
        allowManualEntry: false,
        displayOrder: 2
      },
      {
        id: '1133',
        code: '1133',
        parentId: '1130',
        name: 'ذمم عملاء الوكالات',
        nameEn: 'Agency Receivables',
        type: AccountType.ASSET,
        nature: AccountNature.DEBIT,
        level: 3,
        isParent: false,
        isActive: true,
        status: AccountStatus.ACTIVE,
        balance: 0,
        openingBalance: 0,
        currency: 'SAR',
        isSystemAccount: true,
        allowManualEntry: false,
        displayOrder: 3
      },
      {
        id: '1134',
        code: '1134',
        parentId: '1130',
        name: 'حساب العملاء الآجل',
        nameEn: 'Customers Deferred Account',
        type: AccountType.ASSET,
        nature: AccountNature.DEBIT,
        level: 3,
        isParent: true,
        isActive: true,
        status: AccountStatus.ACTIVE,
        balance: 0,
        openingBalance: 0,
        currency: 'SAR',
        isSystemAccount: true,
        allowManualEntry: false,
        displayOrder: 4
      },
      {
        id: '11341',
        code: '11341',
        parentId: '1134',
        name: 'ذمم عملاء آجل - عام',
        nameEn: 'Deferred Receivables - General',
        type: AccountType.ASSET,
        nature: AccountNature.DEBIT,
        level: 4,
        isParent: false,
        isActive: true,
        status: AccountStatus.ACTIVE,
        balance: 0,
        openingBalance: 0,
        currency: 'SAR',
        isSystemAccount: true,
        allowManualEntry: true,
        displayOrder: 1
      },
      {
        id: '11342',
        code: '11342',
        parentId: '1134',
        name: 'ذمم عملاء آجل - وكالات',
        nameEn: 'Deferred Receivables - Agencies',
        type: AccountType.ASSET,
        nature: AccountNature.DEBIT,
        level: 4,
        isParent: false,
        isActive: true,
        status: AccountStatus.ACTIVE,
        balance: 0,
        openingBalance: 0,
        currency: 'SAR',
        isSystemAccount: true,
        allowManualEntry: true,
        displayOrder: 2
      },
      {
        id: '11343',
        code: '11343',
        parentId: '1134',
        name: 'ذمم عملاء آجل - B2B',
        nameEn: 'Deferred Receivables - B2B',
        type: AccountType.ASSET,
        nature: AccountNature.DEBIT,
        level: 4,
        isParent: false,
        isActive: true,
        status: AccountStatus.ACTIVE,
        balance: 0,
        openingBalance: 0,
        currency: 'SAR',
        isSystemAccount: true,
        allowManualEntry: true,
        displayOrder: 3
      },
      {
        id: '1140',
        code: '1140',
        parentId: '1100',
        name: 'المخزون',
        nameEn: 'Inventory',
        type: AccountType.ASSET,
        nature: AccountNature.DEBIT,
        level: 2,
        isParent: true,
        isActive: true,
        status: AccountStatus.ACTIVE,
        balance: 0,
        openingBalance: 0,
        currency: 'SAR',
        isSystemAccount: true,
        allowManualEntry: false,
        displayOrder: 4
      },
      {
        id: '1141',
        code: '1141',
        parentId: '1140',
        name: 'مخزون المطعم',
        nameEn: 'Restaurant Inventory',
        type: AccountType.ASSET,
        nature: AccountNature.DEBIT,
        level: 3,
        isParent: false,
        isActive: true,
        status: AccountStatus.ACTIVE,
        balance: 0,
        openingBalance: 0,
        currency: 'SAR',
        isSystemAccount: false,
        allowManualEntry: true,
        displayOrder: 1
      },
      {
        id: '1142',
        code: '1142',
        parentId: '1140',
        name: 'مخزون التنظيف',
        nameEn: 'Cleaning Supplies Inventory',
        type: AccountType.ASSET,
        nature: AccountNature.DEBIT,
        level: 3,
        isParent: false,
        isActive: true,
        status: AccountStatus.ACTIVE,
        balance: 0,
        openingBalance: 0,
        currency: 'SAR',
        isSystemAccount: false,
        allowManualEntry: true,
        displayOrder: 2
      },
      {
        id: '1143',
        code: '1143',
        parentId: '1140',
        name: 'مخزون الصيانة',
        nameEn: 'Maintenance Inventory',
        type: AccountType.ASSET,
        nature: AccountNature.DEBIT,
        level: 3,
        isParent: false,
        isActive: true,
        status: AccountStatus.ACTIVE,
        balance: 0,
        openingBalance: 0,
        currency: 'SAR',
        isSystemAccount: false,
        allowManualEntry: true,
        displayOrder: 3
      },
      {
        id: '1150',
        code: '1150',
        parentId: '1100',
        name: 'مصروفات مدفوعة مقدماً',
        nameEn: 'Prepaid Expenses',
        type: AccountType.ASSET,
        nature: AccountNature.DEBIT,
        level: 2,
        isParent: true,
        isActive: true,
        status: AccountStatus.ACTIVE,
        balance: 0,
        openingBalance: 0,
        currency: 'SAR',
        isSystemAccount: true,
        allowManualEntry: true,
        displayOrder: 5
      },
      {
        id: '1151',
        code: '1151',
        parentId: '1150',
        name: 'إيجار مدفوع مقدماً',
        nameEn: 'Prepaid Rent',
        type: AccountType.ASSET,
        nature: AccountNature.DEBIT,
        level: 3,
        isParent: false,
        isActive: true,
        status: AccountStatus.ACTIVE,
        balance: 0,
        openingBalance: 0,
        currency: 'SAR',
        isSystemAccount: false,
        allowManualEntry: true,
        displayOrder: 1
      },
      {
        id: '1152',
        code: '1152',
        parentId: '1150',
        name: 'تأمين مدفوع مقدماً',
        nameEn: 'Prepaid Insurance',
        type: AccountType.ASSET,
        nature: AccountNature.DEBIT,
        level: 3,
        isParent: false,
        isActive: true,
        status: AccountStatus.ACTIVE,
        balance: 0,
        openingBalance: 0,
        currency: 'SAR',
        isSystemAccount: false,
        allowManualEntry: true,
        displayOrder: 2
      },

      // 1.2 Fixed Assets - الأصول الثابتة (12xx)
      {
        id: '1200',
        code: '1200',
        name: 'الأصول الثابتة',
        nameEn: 'Fixed Assets',
        type: AccountType.ASSET,
        nature: AccountNature.DEBIT,
        level: 1,
        isParent: true,
        isActive: true,
        status: AccountStatus.ACTIVE,
        balance: 0,
        openingBalance: 0,
        currency: 'SAR',
        isSystemAccount: true,
        allowManualEntry: false,
        displayOrder: 2
      },
      {
        id: '1210',
        code: '1210',
        parentId: '1200',
        name: 'الأراضي',
        nameEn: 'Land',
        type: AccountType.ASSET,
        nature: AccountNature.DEBIT,
        level: 2,
        isParent: false,
        isActive: true,
        status: AccountStatus.ACTIVE,
        balance: 0,
        openingBalance: 0,
        currency: 'SAR',
        isSystemAccount: false,
        allowManualEntry: true,
        displayOrder: 1
      },
      {
        id: '1220',
        code: '1220',
        parentId: '1200',
        name: 'المباني',
        nameEn: 'Buildings',
        type: AccountType.ASSET,
        nature: AccountNature.DEBIT,
        level: 2,
        isParent: false,
        isActive: true,
        status: AccountStatus.ACTIVE,
        balance: 0,
        openingBalance: 0,
        currency: 'SAR',
        isSystemAccount: false,
        allowManualEntry: true,
        displayOrder: 2
      },
      {
        id: '1230',
        code: '1230',
        parentId: '1200',
        name: 'معدات وأجهزة',
        nameEn: 'Equipment and Machinery',
        type: AccountType.ASSET,
        nature: AccountNature.DEBIT,
        level: 2,
        isParent: true,
        isActive: true,
        status: AccountStatus.ACTIVE,
        balance: 0,
        openingBalance: 0,
        currency: 'SAR',
        isSystemAccount: true,
        allowManualEntry: false,
        displayOrder: 3
      },
      {
        id: '1231',
        code: '1231',
        parentId: '1230',
        name: 'معدات المطعم',
        nameEn: 'Restaurant Equipment',
        type: AccountType.ASSET,
        nature: AccountNature.DEBIT,
        level: 3,
        isParent: false,
        isActive: true,
        status: AccountStatus.ACTIVE,
        balance: 0,
        openingBalance: 0,
        currency: 'SAR',
        isSystemAccount: false,
        allowManualEntry: true,
        displayOrder: 1
      },
      {
        id: '1232',
        code: '1232',
        parentId: '1230',
        name: 'معدات الغرف',
        nameEn: 'Room Equipment',
        type: AccountType.ASSET,
        nature: AccountNature.DEBIT,
        level: 3,
        isParent: false,
        isActive: true,
        status: AccountStatus.ACTIVE,
        balance: 0,
        openingBalance: 0,
        currency: 'SAR',
        isSystemAccount: false,
        allowManualEntry: true,
        displayOrder: 2
      },
      {
        id: '1233',
        code: '1233',
        parentId: '1230',
        name: 'أجهزة الحاسب الآلي',
        nameEn: 'Computer Equipment',
        type: AccountType.ASSET,
        nature: AccountNature.DEBIT,
        level: 3,
        isParent: false,
        isActive: true,
        status: AccountStatus.ACTIVE,
        balance: 0,
        openingBalance: 0,
        currency: 'SAR',
        isSystemAccount: false,
        allowManualEntry: true,
        displayOrder: 3
      },
      {
        id: '1240',
        code: '1240',
        parentId: '1200',
        name: 'السيارات',
        nameEn: 'Vehicles',
        type: AccountType.ASSET,
        nature: AccountNature.DEBIT,
        level: 2,
        isParent: false,
        isActive: true,
        status: AccountStatus.ACTIVE,
        balance: 0,
        openingBalance: 0,
        currency: 'SAR',
        isSystemAccount: false,
        allowManualEntry: true,
        displayOrder: 4
      },
      {
        id: '1250',
        code: '1250',
        parentId: '1200',
        name: 'مخصص إهلاك الأصول الثابتة',
        nameEn: 'Accumulated Depreciation',
        type: AccountType.ASSET,
        nature: AccountNature.CREDIT, // Contra Asset Account
        level: 2,
        isParent: true,
        isActive: true,
        status: AccountStatus.ACTIVE,
        balance: 0,
        openingBalance: 0,
        currency: 'SAR',
        isSystemAccount: true,
        allowManualEntry: false,
        displayOrder: 5
      },

      // ============================================
      // 2. LIABILITIES - الخصوم (2xxx)
      // ============================================
      
      // 2.1 Current Liabilities - الخصوم المتداولة (21xx)
      {
        id: '2100',
        code: '2100',
        name: 'الخصوم المتداولة',
        nameEn: 'Current Liabilities',
        type: AccountType.LIABILITY,
        nature: AccountNature.CREDIT,
        level: 1,
        isParent: true,
        isActive: true,
        status: AccountStatus.ACTIVE,
        balance: 0,
        openingBalance: 0,
        currency: 'SAR',
        isSystemAccount: true,
        allowManualEntry: false,
        displayOrder: 3
      },
      {
        id: '2110',
        code: '2110',
        parentId: '2100',
        name: 'الموردون والدائنون',
        nameEn: 'Accounts Payable',
        type: AccountType.LIABILITY,
        nature: AccountNature.CREDIT,
        level: 2,
        isParent: true,
        isActive: true,
        status: AccountStatus.ACTIVE,
        balance: 0,
        openingBalance: 0,
        currency: 'SAR',
        isSystemAccount: true,
        allowManualEntry: false,
        displayOrder: 1
      },
      {
        id: '2111',
        code: '2111',
        parentId: '2110',
        name: 'ذمم موردين',
        nameEn: 'Suppliers Payable',
        type: AccountType.LIABILITY,
        nature: AccountNature.CREDIT,
        level: 3,
        isParent: false,
        isActive: true,
        status: AccountStatus.ACTIVE,
        balance: 0,
        openingBalance: 0,
        currency: 'SAR',
        isSystemAccount: true,
        allowManualEntry: false,
        displayOrder: 1
      },
      {
        id: '2112',
        code: '2112',
        parentId: '2110',
        name: 'ذمم موردين الخدمات',
        nameEn: 'Service Providers Payable',
        type: AccountType.LIABILITY,
        nature: AccountNature.CREDIT,
        level: 3,
        isParent: false,
        isActive: true,
        status: AccountStatus.ACTIVE,
        balance: 0,
        openingBalance: 0,
        currency: 'SAR',
        isSystemAccount: true,
        allowManualEntry: false,
        displayOrder: 2
      },
      {
        id: '2120',
        code: '2120',
        parentId: '2100',
        name: 'الضرائب المستحقة',
        nameEn: 'Taxes Payable',
        type: AccountType.LIABILITY,
        nature: AccountNature.CREDIT,
        level: 2,
        isParent: true,
        isActive: true,
        status: AccountStatus.ACTIVE,
        balance: 0,
        openingBalance: 0,
        currency: 'SAR',
        isSystemAccount: true,
        allowManualEntry: false,
        displayOrder: 2
      },
      {
        id: '2121',
        code: '2121',
        parentId: '2120',
        name: 'ضريبة القيمة المضافة المستحقة',
        nameEn: 'VAT Payable',
        type: AccountType.LIABILITY,
        nature: AccountNature.CREDIT,
        level: 3,
        isParent: false,
        isActive: true,
        status: AccountStatus.ACTIVE,
        balance: 0,
        openingBalance: 0,
        currency: 'SAR',
        isSystemAccount: true,
        allowManualEntry: false,
        displayOrder: 1
      },
      {
        id: '2122',
        code: '2122',
        parentId: '2120',
        name: 'ضريبة البلدية المستحقة',
        nameEn: 'Municipal Tax Payable',
        type: AccountType.LIABILITY,
        nature: AccountNature.CREDIT,
        level: 3,
        isParent: false,
        isActive: true,
        status: AccountStatus.ACTIVE,
        balance: 0,
        openingBalance: 0,
        currency: 'SAR',
        isSystemAccount: true,
        allowManualEntry: false,
        displayOrder: 2
      },
      {
        id: '2130',
        code: '2130',
        parentId: '2100',
        name: 'الرواتب والأجور المستحقة',
        nameEn: 'Salaries and Wages Payable',
        type: AccountType.LIABILITY,
        nature: AccountNature.CREDIT,
        level: 2,
        isParent: false,
        isActive: true,
        status: AccountStatus.ACTIVE,
        balance: 0,
        openingBalance: 0,
        currency: 'SAR',
        isSystemAccount: true,
        allowManualEntry: false,
        displayOrder: 3
      },
      {
        id: '2140',
        code: '2140',
        parentId: '2100',
        name: 'إيرادات مستحقة القبض',
        nameEn: 'Unearned Revenue',
        type: AccountType.LIABILITY,
        nature: AccountNature.CREDIT,
        level: 2,
        isParent: true,
        isActive: true,
        status: AccountStatus.ACTIVE,
        balance: 0,
        openingBalance: 0,
        currency: 'SAR',
        isSystemAccount: true,
        allowManualEntry: false,
        displayOrder: 4
      },
      {
        id: '2141',
        code: '2141',
        parentId: '2140',
        name: 'إيرادات حجوزات مقدمة',
        nameEn: 'Advance Booking Revenue',
        type: AccountType.LIABILITY,
        nature: AccountNature.CREDIT,
        level: 3,
        isParent: false,
        isActive: true,
        status: AccountStatus.ACTIVE,
        balance: 0,
        openingBalance: 0,
        currency: 'SAR',
        isSystemAccount: true,
        allowManualEntry: false,
        displayOrder: 1
      },

      // 2.2 Long-term Liabilities - الخصوم طويلة الأجل (22xx)
      {
        id: '2200',
        code: '2200',
        name: 'الخصوم طويلة الأجل',
        nameEn: 'Long-term Liabilities',
        type: AccountType.LIABILITY,
        nature: AccountNature.CREDIT,
        level: 1,
        isParent: true,
        isActive: true,
        status: AccountStatus.ACTIVE,
        balance: 0,
        openingBalance: 0,
        currency: 'SAR',
        isSystemAccount: true,
        allowManualEntry: false,
        displayOrder: 4
      },
      {
        id: '2210',
        code: '2210',
        parentId: '2200',
        name: 'القروض طويلة الأجل',
        nameEn: 'Long-term Loans',
        type: AccountType.LIABILITY,
        nature: AccountNature.CREDIT,
        level: 2,
        isParent: false,
        isActive: true,
        status: AccountStatus.ACTIVE,
        balance: 0,
        openingBalance: 0,
        currency: 'SAR',
        isSystemAccount: false,
        allowManualEntry: true,
        displayOrder: 1
      },

      // ============================================
      // 3. EQUITY - حقوق الملكية (3xxx)
      // ============================================
      {
        id: '3100',
        code: '3100',
        name: 'حقوق الملكية',
        nameEn: 'Equity',
        type: AccountType.EQUITY,
        nature: AccountNature.CREDIT,
        level: 1,
        isParent: true,
        isActive: true,
        status: AccountStatus.ACTIVE,
        balance: 0,
        openingBalance: 0,
        currency: 'SAR',
        isSystemAccount: true,
        allowManualEntry: false,
        displayOrder: 5
      },
      {
        id: '3110',
        code: '3110',
        parentId: '3100',
        name: 'رأس المال',
        nameEn: 'Capital',
        type: AccountType.EQUITY,
        nature: AccountNature.CREDIT,
        level: 2,
        isParent: false,
        isActive: true,
        status: AccountStatus.ACTIVE,
        balance: 0,
        openingBalance: 0,
        currency: 'SAR',
        isSystemAccount: true,
        allowManualEntry: true,
        displayOrder: 1
      },
      {
        id: '3120',
        code: '3120',
        parentId: '3100',
        name: 'الأرباح المحتجزة',
        nameEn: 'Retained Earnings',
        type: AccountType.EQUITY,
        nature: AccountNature.CREDIT,
        level: 2,
        isParent: false,
        isActive: true,
        status: AccountStatus.ACTIVE,
        balance: 0,
        openingBalance: 0,
        currency: 'SAR',
        isSystemAccount: true,
        allowManualEntry: false,
        displayOrder: 2
      },
      {
        id: '3130',
        code: '3130',
        parentId: '3100',
        name: 'صافي الربح/الخسارة',
        nameEn: 'Net Profit/Loss',
        type: AccountType.EQUITY,
        nature: AccountNature.CREDIT,
        level: 2,
        isParent: false,
        isActive: true,
        status: AccountStatus.ACTIVE,
        balance: 0,
        openingBalance: 0,
        currency: 'SAR',
        isSystemAccount: true,
        allowManualEntry: false,
        displayOrder: 3
      },

      // ============================================
      // 4. REVENUE - الإيرادات (4xxx)
      // ============================================
      {
        id: '4100',
        code: '4100',
        name: 'الإيرادات',
        nameEn: 'Revenue',
        type: AccountType.REVENUE,
        nature: AccountNature.CREDIT,
        level: 1,
        isParent: true,
        isActive: true,
        status: AccountStatus.ACTIVE,
        balance: 0,
        openingBalance: 0,
        currency: 'SAR',
        isSystemAccount: true,
        allowManualEntry: false,
        displayOrder: 6
      },
      {
        id: '4110',
        code: '4110',
        parentId: '4100',
        name: 'إيرادات الحجوزات',
        nameEn: 'Booking Revenue',
        type: AccountType.REVENUE,
        nature: AccountNature.CREDIT,
        level: 2,
        isParent: true,
        isActive: true,
        status: AccountStatus.ACTIVE,
        balance: 0,
        openingBalance: 0,
        currency: 'SAR',
        isSystemAccount: true,
        allowManualEntry: false,
        displayOrder: 1
      },
      {
        id: '4111',
        code: '4111',
        parentId: '4110',
        name: 'إيرادات إيجار الغرف',
        nameEn: 'Room Rental Revenue',
        type: AccountType.REVENUE,
        nature: AccountNature.CREDIT,
        level: 3,
        isParent: false,
        isActive: true,
        status: AccountStatus.ACTIVE,
        balance: 0,
        openingBalance: 0,
        currency: 'SAR',
        isSystemAccount: true,
        allowManualEntry: false,
        displayOrder: 1
      },
      {
        id: '4112',
        code: '4112',
        parentId: '4110',
        name: 'إيرادات إيجار الشقق',
        nameEn: 'Apartment Rental Revenue',
        type: AccountType.REVENUE,
        nature: AccountNature.CREDIT,
        level: 3,
        isParent: false,
        isActive: true,
        status: AccountStatus.ACTIVE,
        balance: 0,
        openingBalance: 0,
        currency: 'SAR',
        isSystemAccount: true,
        allowManualEntry: false,
        displayOrder: 2
      },
      {
        id: '4120',
        code: '4120',
        parentId: '4100',
        name: 'إيرادات المطعم',
        nameEn: 'Restaurant Revenue',
        type: AccountType.REVENUE,
        nature: AccountNature.CREDIT,
        level: 2,
        isParent: true,
        isActive: true,
        status: AccountStatus.ACTIVE,
        balance: 0,
        openingBalance: 0,
        currency: 'SAR',
        isSystemAccount: true,
        allowManualEntry: false,
        displayOrder: 2
      },
      {
        id: '4121',
        code: '4121',
        parentId: '4120',
        name: 'إيرادات الإفطار',
        nameEn: 'Breakfast Revenue',
        type: AccountType.REVENUE,
        nature: AccountNature.CREDIT,
        level: 3,
        isParent: false,
        isActive: true,
        status: AccountStatus.ACTIVE,
        balance: 0,
        openingBalance: 0,
        currency: 'SAR',
        isSystemAccount: true,
        allowManualEntry: false,
        displayOrder: 1
      },
      {
        id: '4122',
        code: '4122',
        parentId: '4120',
        name: 'إيرادات الغداء',
        nameEn: 'Lunch Revenue',
        type: AccountType.REVENUE,
        nature: AccountNature.CREDIT,
        level: 3,
        isParent: false,
        isActive: true,
        status: AccountStatus.ACTIVE,
        balance: 0,
        openingBalance: 0,
        currency: 'SAR',
        isSystemAccount: true,
        allowManualEntry: false,
        displayOrder: 2
      },
      {
        id: '4123',
        code: '4123',
        parentId: '4120',
        name: 'إيرادات العشاء',
        nameEn: 'Dinner Revenue',
        type: AccountType.REVENUE,
        nature: AccountNature.CREDIT,
        level: 3,
        isParent: false,
        isActive: true,
        status: AccountStatus.ACTIVE,
        balance: 0,
        openingBalance: 0,
        currency: 'SAR',
        isSystemAccount: true,
        allowManualEntry: false,
        displayOrder: 3
      },
      {
        id: '4130',
        code: '4130',
        parentId: '4100',
        name: 'إيرادات الخدمات',
        nameEn: 'Service Revenue',
        type: AccountType.REVENUE,
        nature: AccountNature.CREDIT,
        level: 2,
        isParent: true,
        isActive: true,
        status: AccountStatus.ACTIVE,
        balance: 0,
        openingBalance: 0,
        currency: 'SAR',
        isSystemAccount: true,
        allowManualEntry: false,
        displayOrder: 3
      },
      {
        id: '4131',
        code: '4131',
        parentId: '4130',
        name: 'إيرادات خدمة التنظيف',
        nameEn: 'Cleaning Service Revenue',
        type: AccountType.REVENUE,
        nature: AccountNature.CREDIT,
        level: 3,
        isParent: false,
        isActive: true,
        status: AccountStatus.ACTIVE,
        balance: 0,
        openingBalance: 0,
        currency: 'SAR',
        isSystemAccount: true,
        allowManualEntry: false,
        displayOrder: 1
      },
      {
        id: '4132',
        code: '4132',
        parentId: '4130',
        name: 'إيرادات خدمة الغسيل',
        nameEn: 'Laundry Service Revenue',
        type: AccountType.REVENUE,
        nature: AccountNature.CREDIT,
        level: 3,
        isParent: false,
        isActive: true,
        status: AccountStatus.ACTIVE,
        balance: 0,
        openingBalance: 0,
        currency: 'SAR',
        isSystemAccount: true,
        allowManualEntry: false,
        displayOrder: 2
      },
      {
        id: '4133',
        code: '4133',
        parentId: '4130',
        name: 'إيرادات خدمة النقل',
        nameEn: 'Transportation Service Revenue',
        type: AccountType.REVENUE,
        nature: AccountNature.CREDIT,
        level: 3,
        isParent: false,
        isActive: true,
        status: AccountStatus.ACTIVE,
        balance: 0,
        openingBalance: 0,
        currency: 'SAR',
        isSystemAccount: true,
        allowManualEntry: false,
        displayOrder: 3
      },
      {
        id: '4140',
        code: '4140',
        parentId: '4100',
        name: 'إيرادات أخرى',
        nameEn: 'Other Revenue',
        type: AccountType.REVENUE,
        nature: AccountNature.CREDIT,
        level: 2,
        isParent: true,
        isActive: true,
        status: AccountStatus.ACTIVE,
        balance: 0,
        openingBalance: 0,
        currency: 'SAR',
        isSystemAccount: true,
        allowManualEntry: false,
        displayOrder: 4
      },
      {
        id: '4141',
        code: '4141',
        parentId: '4140',
        name: 'إيرادات الإلغاء والغرامات',
        nameEn: 'Cancellation and Penalty Revenue',
        type: AccountType.REVENUE,
        nature: AccountNature.CREDIT,
        level: 3,
        isParent: false,
        isActive: true,
        status: AccountStatus.ACTIVE,
        balance: 0,
        openingBalance: 0,
        currency: 'SAR',
        isSystemAccount: true,
        allowManualEntry: false,
        displayOrder: 1
      },
      {
        id: '4150',
        code: '4150',
        parentId: '4100',
        name: 'خصومات المبيعات',
        nameEn: 'Sales Discounts',
        type: AccountType.REVENUE,
        nature: AccountNature.DEBIT, // Contra Revenue Account
        level: 2,
        isParent: false,
        isActive: true,
        status: AccountStatus.ACTIVE,
        balance: 0,
        openingBalance: 0,
        currency: 'SAR',
        isSystemAccount: true,
        allowManualEntry: false,
        displayOrder: 5
      },

      // ============================================
      // 5. EXPENSES - المصروفات (5xxx)
      // ============================================
      {
        id: '5100',
        code: '5100',
        name: 'المصروفات',
        nameEn: 'Expenses',
        type: AccountType.EXPENSE,
        nature: AccountNature.DEBIT,
        level: 1,
        isParent: true,
        isActive: true,
        status: AccountStatus.ACTIVE,
        balance: 0,
        openingBalance: 0,
        currency: 'SAR',
        isSystemAccount: true,
        allowManualEntry: false,
        displayOrder: 7
      },
      {
        id: '5110',
        code: '5110',
        parentId: '5100',
        name: 'تكلفة البضاعة المباعة',
        nameEn: 'Cost of Goods Sold',
        type: AccountType.EXPENSE,
        nature: AccountNature.DEBIT,
        level: 2,
        isParent: true,
        isActive: true,
        status: AccountStatus.ACTIVE,
        balance: 0,
        openingBalance: 0,
        currency: 'SAR',
        isSystemAccount: true,
        allowManualEntry: false,
        displayOrder: 1
      },
      {
        id: '5111',
        code: '5111',
        parentId: '5110',
        name: 'تكلفة المطعم',
        nameEn: 'Restaurant Cost',
        type: AccountType.EXPENSE,
        nature: AccountNature.DEBIT,
        level: 3,
        isParent: false,
        isActive: true,
        status: AccountStatus.ACTIVE,
        balance: 0,
        openingBalance: 0,
        currency: 'SAR',
        isSystemAccount: true,
        allowManualEntry: false,
        displayOrder: 1
      },
      {
        id: '5120',
        code: '5120',
        parentId: '5100',
        name: 'مصروفات التشغيل',
        nameEn: 'Operating Expenses',
        type: AccountType.EXPENSE,
        nature: AccountNature.DEBIT,
        level: 2,
        isParent: true,
        isActive: true,
        status: AccountStatus.ACTIVE,
        balance: 0,
        openingBalance: 0,
        currency: 'SAR',
        isSystemAccount: true,
        allowManualEntry: false,
        displayOrder: 2
      },
      {
        id: '5121',
        code: '5121',
        parentId: '5120',
        name: 'الرواتب والأجور',
        nameEn: 'Salaries and Wages',
        type: AccountType.EXPENSE,
        nature: AccountNature.DEBIT,
        level: 3,
        isParent: false,
        isActive: true,
        status: AccountStatus.ACTIVE,
        balance: 0,
        openingBalance: 0,
        currency: 'SAR',
        isSystemAccount: true,
        allowManualEntry: false,
        displayOrder: 1
      },
      {
        id: '5122',
        code: '5122',
        parentId: '5120',
        name: 'مصروفات التأمين',
        nameEn: 'Insurance Expenses',
        type: AccountType.EXPENSE,
        nature: AccountNature.DEBIT,
        level: 3,
        isParent: false,
        isActive: true,
        status: AccountStatus.ACTIVE,
        balance: 0,
        openingBalance: 0,
        currency: 'SAR',
        isSystemAccount: false,
        allowManualEntry: true,
        displayOrder: 2
      },
      {
        id: '5123',
        code: '5123',
        parentId: '5120',
        name: 'مصروفات الإيجار',
        nameEn: 'Rent Expenses',
        type: AccountType.EXPENSE,
        nature: AccountNature.DEBIT,
        level: 3,
        isParent: false,
        isActive: true,
        status: AccountStatus.ACTIVE,
        balance: 0,
        openingBalance: 0,
        currency: 'SAR',
        isSystemAccount: false,
        allowManualEntry: true,
        displayOrder: 3
      },
      {
        id: '5124',
        code: '5124',
        parentId: '5120',
        name: 'مصروفات المرافق',
        nameEn: 'Utilities Expenses',
        type: AccountType.EXPENSE,
        nature: AccountNature.DEBIT,
        level: 3,
        isParent: true,
        isActive: true,
        status: AccountStatus.ACTIVE,
        balance: 0,
        openingBalance: 0,
        currency: 'SAR',
        isSystemAccount: true,
        allowManualEntry: false,
        displayOrder: 4
      },
      {
        id: '5124-1',
        code: '5124-1',
        parentId: '5124',
        name: 'مصروفات الكهرباء',
        nameEn: 'Electricity Expenses',
        type: AccountType.EXPENSE,
        nature: AccountNature.DEBIT,
        level: 4,
        isParent: false,
        isActive: true,
        status: AccountStatus.ACTIVE,
        balance: 0,
        openingBalance: 0,
        currency: 'SAR',
        isSystemAccount: false,
        allowManualEntry: true,
        displayOrder: 1
      },
      {
        id: '5124-2',
        code: '5124-2',
        parentId: '5124',
        name: 'مصروفات الماء',
        nameEn: 'Water Expenses',
        type: AccountType.EXPENSE,
        nature: AccountNature.DEBIT,
        level: 4,
        isParent: false,
        isActive: true,
        status: AccountStatus.ACTIVE,
        balance: 0,
        openingBalance: 0,
        currency: 'SAR',
        isSystemAccount: false,
        allowManualEntry: true,
        displayOrder: 2
      },
      {
        id: '5124-3',
        code: '5124-3',
        parentId: '5124',
        name: 'مصروفات الهاتف والإنترنت',
        nameEn: 'Phone and Internet Expenses',
        type: AccountType.EXPENSE,
        nature: AccountNature.DEBIT,
        level: 4,
        isParent: false,
        isActive: true,
        status: AccountStatus.ACTIVE,
        balance: 0,
        openingBalance: 0,
        currency: 'SAR',
        isSystemAccount: false,
        allowManualEntry: true,
        displayOrder: 3
      },
      {
        id: '5125',
        code: '5125',
        parentId: '5120',
        name: 'مصروفات الصيانة',
        nameEn: 'Maintenance Expenses',
        type: AccountType.EXPENSE,
        nature: AccountNature.DEBIT,
        level: 3,
        isParent: true,
        isActive: true,
        status: AccountStatus.ACTIVE,
        balance: 0,
        openingBalance: 0,
        currency: 'SAR',
        isSystemAccount: true,
        allowManualEntry: false,
        displayOrder: 5
      },
      {
        id: '5125-1',
        code: '5125-1',
        parentId: '5125',
        name: 'صيانة الغرف',
        nameEn: 'Room Maintenance',
        type: AccountType.EXPENSE,
        nature: AccountNature.DEBIT,
        level: 4,
        isParent: false,
        isActive: true,
        status: AccountStatus.ACTIVE,
        balance: 0,
        openingBalance: 0,
        currency: 'SAR',
        isSystemAccount: false,
        allowManualEntry: true,
        displayOrder: 1
      },
      {
        id: '5125-2',
        code: '5125-2',
        parentId: '5125',
        name: 'صيانة المعدات',
        nameEn: 'Equipment Maintenance',
        type: AccountType.EXPENSE,
        nature: AccountNature.DEBIT,
        level: 4,
        isParent: false,
        isActive: true,
        status: AccountStatus.ACTIVE,
        balance: 0,
        openingBalance: 0,
        currency: 'SAR',
        isSystemAccount: false,
        allowManualEntry: true,
        displayOrder: 2
      },
      {
        id: '5126',
        code: '5126',
        parentId: '5120',
        name: 'مصروفات التنظيف',
        nameEn: 'Cleaning Expenses',
        type: AccountType.EXPENSE,
        nature: AccountNature.DEBIT,
        level: 3,
        isParent: false,
        isActive: true,
        status: AccountStatus.ACTIVE,
        balance: 0,
        openingBalance: 0,
        currency: 'SAR',
        isSystemAccount: false,
        allowManualEntry: true,
        displayOrder: 6
      },
      {
        id: '5130',
        code: '5130',
        parentId: '5100',
        name: 'مصروفات الإدارة',
        nameEn: 'Administrative Expenses',
        type: AccountType.EXPENSE,
        nature: AccountNature.DEBIT,
        level: 2,
        isParent: true,
        isActive: true,
        status: AccountStatus.ACTIVE,
        balance: 0,
        openingBalance: 0,
        currency: 'SAR',
        isSystemAccount: true,
        allowManualEntry: false,
        displayOrder: 3
      },
      {
        id: '5131',
        code: '5131',
        parentId: '5130',
        name: 'مصروفات المكتب',
        nameEn: 'Office Expenses',
        type: AccountType.EXPENSE,
        nature: AccountNature.DEBIT,
        level: 3,
        isParent: false,
        isActive: true,
        status: AccountStatus.ACTIVE,
        balance: 0,
        openingBalance: 0,
        currency: 'SAR',
        isSystemAccount: false,
        allowManualEntry: true,
        displayOrder: 1
      },
      {
        id: '5132',
        code: '5132',
        parentId: '5130',
        name: 'مصروفات الاتصالات',
        nameEn: 'Communication Expenses',
        type: AccountType.EXPENSE,
        nature: AccountNature.DEBIT,
        level: 3,
        isParent: false,
        isActive: true,
        status: AccountStatus.ACTIVE,
        balance: 0,
        openingBalance: 0,
        currency: 'SAR',
        isSystemAccount: false,
        allowManualEntry: true,
        displayOrder: 2
      },
      {
        id: '5133',
        code: '5133',
        parentId: '5130',
        name: 'مصروفات المحاسبة والمراجعة',
        nameEn: 'Accounting and Auditing Expenses',
        type: AccountType.EXPENSE,
        nature: AccountNature.DEBIT,
        level: 3,
        isParent: false,
        isActive: true,
        status: AccountStatus.ACTIVE,
        balance: 0,
        openingBalance: 0,
        currency: 'SAR',
        isSystemAccount: false,
        allowManualEntry: true,
        displayOrder: 3
      },
      {
        id: '5134',
        code: '5134',
        parentId: '5130',
        name: 'مصروفات التأمينات الاجتماعية',
        nameEn: 'Social Insurance Expenses',
        type: AccountType.EXPENSE,
        nature: AccountNature.DEBIT,
        level: 3,
        isParent: false,
        isActive: true,
        status: AccountStatus.ACTIVE,
        balance: 0,
        openingBalance: 0,
        currency: 'SAR',
        isSystemAccount: true,
        allowManualEntry: false,
        displayOrder: 4
      },
      {
        id: '5140',
        code: '5140',
        parentId: '5100',
        name: 'مصروفات التسويق والإعلان',
        nameEn: 'Marketing and Advertising Expenses',
        type: AccountType.EXPENSE,
        nature: AccountNature.DEBIT,
        level: 2,
        isParent: true,
        isActive: true,
        status: AccountStatus.ACTIVE,
        balance: 0,
        openingBalance: 0,
        currency: 'SAR',
        isSystemAccount: true,
        allowManualEntry: false,
        displayOrder: 4
      },
      {
        id: '5141',
        code: '5141',
        parentId: '5140',
        name: 'مصروفات الإعلان',
        nameEn: 'Advertising Expenses',
        type: AccountType.EXPENSE,
        nature: AccountNature.DEBIT,
        level: 3,
        isParent: false,
        isActive: true,
        status: AccountStatus.ACTIVE,
        balance: 0,
        openingBalance: 0,
        currency: 'SAR',
        isSystemAccount: false,
        allowManualEntry: true,
        displayOrder: 1
      },
      {
        id: '5142',
        code: '5142',
        parentId: '5140',
        name: 'مصروفات منصات الحجز',
        nameEn: 'Booking Platform Expenses',
        type: AccountType.EXPENSE,
        nature: AccountNature.DEBIT,
        level: 3,
        isParent: false,
        isActive: true,
        status: AccountStatus.ACTIVE,
        balance: 0,
        openingBalance: 0,
        currency: 'SAR',
        isSystemAccount: true,
        allowManualEntry: false,
        displayOrder: 2
      },
      {
        id: '5150',
        code: '5150',
        parentId: '5100',
        name: 'مصروفات الإهلاك',
        nameEn: 'Depreciation Expenses',
        type: AccountType.EXPENSE,
        nature: AccountNature.DEBIT,
        level: 2,
        isParent: true,
        isActive: true,
        status: AccountStatus.ACTIVE,
        balance: 0,
        openingBalance: 0,
        currency: 'SAR',
        isSystemAccount: true,
        allowManualEntry: false,
        displayOrder: 5
      },
      {
        id: '5151',
        code: '5151',
        parentId: '5150',
        name: 'إهلاك المباني',
        nameEn: 'Building Depreciation',
        type: AccountType.EXPENSE,
        nature: AccountNature.DEBIT,
        level: 3,
        isParent: false,
        isActive: true,
        status: AccountStatus.ACTIVE,
        balance: 0,
        openingBalance: 0,
        currency: 'SAR',
        isSystemAccount: false,
        allowManualEntry: true,
        displayOrder: 1
      },
      {
        id: '5152',
        code: '5152',
        parentId: '5150',
        name: 'إهلاك المعدات',
        nameEn: 'Equipment Depreciation',
        type: AccountType.EXPENSE,
        nature: AccountNature.DEBIT,
        level: 3,
        isParent: false,
        isActive: true,
        status: AccountStatus.ACTIVE,
        balance: 0,
        openingBalance: 0,
        currency: 'SAR',
        isSystemAccount: false,
        allowManualEntry: true,
        displayOrder: 2
      },
      {
        id: '5160',
        code: '5160',
        parentId: '5100',
        name: 'مصروفات مالية',
        nameEn: 'Financial Expenses',
        type: AccountType.EXPENSE,
        nature: AccountNature.DEBIT,
        level: 2,
        isParent: true,
        isActive: true,
        status: AccountStatus.ACTIVE,
        balance: 0,
        openingBalance: 0,
        currency: 'SAR',
        isSystemAccount: true,
        allowManualEntry: false,
        displayOrder: 6
      },
      {
        id: '5161',
        code: '5161',
        parentId: '5160',
        name: 'فوائد القروض',
        nameEn: 'Loan Interest',
        type: AccountType.EXPENSE,
        nature: AccountNature.DEBIT,
        level: 3,
        isParent: false,
        isActive: true,
        status: AccountStatus.ACTIVE,
        balance: 0,
        openingBalance: 0,
        currency: 'SAR',
        isSystemAccount: false,
        allowManualEntry: true,
        displayOrder: 1
      },
      {
        id: '5162',
        code: '5162',
        parentId: '5160',
        name: 'مصروفات البنك',
        nameEn: 'Bank Charges',
        type: AccountType.EXPENSE,
        nature: AccountNature.DEBIT,
        level: 3,
        isParent: false,
        isActive: true,
        status: AccountStatus.ACTIVE,
        balance: 0,
        openingBalance: 0,
        currency: 'SAR',
        isSystemAccount: false,
        allowManualEntry: true,
        displayOrder: 2
      },
      {
        id: '5170',
        code: '5170',
        parentId: '5100',
        name: 'مصروفات أخرى',
        nameEn: 'Other Expenses',
        type: AccountType.EXPENSE,
        nature: AccountNature.DEBIT,
        level: 2,
        isParent: false,
        isActive: true,
        status: AccountStatus.ACTIVE,
        balance: 0,
        openingBalance: 0,
        currency: 'SAR',
        isSystemAccount: false,
        allowManualEntry: true,
        displayOrder: 7
      }
    ];
  }

  /**
   * Get Accounts by Type
   * الحصول على الحسابات حسب النوع
   */
  static getAccountsByType(type: AccountType): Account[] {
    return this.getAccounts().filter(account => account.type === type);
  }

  /**
   * Get Account by ID
   * الحصول على حساب محدد
   */
  static getAccountById(id: string): Account | undefined {
    return this.getAccounts().find(account => account.id === id);
  }

  /**
   * Get Account by Code
   * الحصول على حساب محدد بالكود
   */
  static getAccountByCode(code: string): Account | undefined {
    return this.getAccounts().find(account => account.code === code);
  }

  /**
   * Get Parent Accounts
   * الحصول على الحسابات الرئيسية فقط
   */
  static getParentAccounts(): Account[] {
    return this.getAccounts().filter(account => account.isParent && account.level <= 2);
  }

  /**
   * Get Child Accounts
   * الحصول على الحسابات الفرعية لحساب معين
   */
  static getChildAccounts(parentId: string): Account[] {
    return this.getAccounts().filter(account => account.parentId === parentId);
  }

  /**
   * Get Account Tree Structure
   * الحصول على هيكل الشجرة المحاسبية
   */
  static getAccountTree(): Account[] {
    const accounts = this.getAccounts();
    const tree: Account[] = [];
    const accountMap = new Map<string, Account & { children?: Account[] }>();

    // Create map of accounts
    accounts.forEach(account => {
      accountMap.set(account.id, { ...account, children: [] });
    });

    // Build tree structure
    accounts.forEach(account => {
      const accountWithChildren = accountMap.get(account.id)!;
      if (account.parentId) {
        const parent = accountMap.get(account.parentId);
        if (parent) {
          parent.children!.push(accountWithChildren);
        }
      } else {
        tree.push(accountWithChildren);
      }
    });

    return tree;
  }

  /**
   * Get Accounts for Dropdown/Select
   * الحصول على الحسابات للقوائم المنسدلة
   */
  static getAccountsForSelect(includeInactive: boolean = false): Array<{ value: string; label: string; labelEn: string }> {
    return this.getAccounts()
      .filter(account => includeInactive || account.isActive)
      .map(account => ({
        value: account.id,
        label: account.name,
        labelEn: account.nameEn
      }));
  }
}
