import { SeroPackageModel, TagBasicModel } from './agent-package.model';

export const mockPackageTags: TagBasicModel[] = [
  { TagID: 1, Name: 'Premium', Description: 'High service level', Color: '#0f766e' },
  { TagID: 2, Name: 'Family', Description: 'Family-friendly package', Color: '#2563eb' },
  { TagID: 3, Name: 'Economy', Description: 'Budget package', Color: '#ea580c' },
  { TagID: 4, Name: 'Ramadan', Description: 'Seasonal package', Color: '#7c3aed' },
];

// Currently using local mock data for frontend prototype. Later this can be replaced with backend API.
export const mockAgentPackages: SeroPackageModel[] = [
  {
    PackageID: 1001,
    PackageCode: 'PKG-2026-001',
    Title: 'Makkah and Madinah Premium Umrah Package',
    Description: 'A complete prototype package copied into the SalamApp package workflow.',
    Price: 7420,
    VerifiedPrice: true,
    BlendedPrice: false,
    StartDate: new Date('2026-06-05'),
    EndDate: new Date('2026-06-15'),
    IsVisaIncluded: true,
    IsActive: true,
    IsByAgent: false,
    ImageUrl: null,
    GuestCount: 45,
    Quantity: 12,
    AddedDate: new Date('2026-05-01T10:30:00'),
    AddedBy: 'Prototype Admin',
    Hotels: [
      {
        Id: 1,
        SeroPackageId: 1001,
        CityId: 1,
        CityName: 'Makkah',
        HotelId: 101,
        HotelName: 'Makkah Grand Hotel',
        DistrictId: 11,
        DistrictName: 'Ajyad',
        DistanceFromHaram: 0.6,
        HotelStar: 5,
        HotelCategoryID: 1,
        HotelCategoryName: 'Five Star',
        RoomTypeID: 1,
        RoomTypeName: 'Double Room',
        NightsCount: 5,
        RoomCount: 10,
        Price: 3250,
      },
      {
        Id: 2,
        SeroPackageId: 1001,
        CityId: 2,
        CityName: 'Madinah',
        HotelId: 201,
        HotelName: 'Madinah Rawdah Hotel',
        DistrictId: 21,
        DistrictName: 'Central Area',
        DistanceFromHaram: 0.4,
        HotelStar: 5,
        HotelCategoryID: 1,
        HotelCategoryName: 'Five Star',
        RoomTypeID: 1,
        RoomTypeName: 'Double Room',
        NightsCount: 5,
        RoomCount: 10,
        Price: 2650,
      },
    ],
    HotelCounts: [
      { Id: 1, SeroPackageId: 1001, CityId: 1, CityName: 'Makkah', NightCount: 5 },
      { Id: 2, SeroPackageId: 1001, CityId: 2, CityName: 'Madinah', NightCount: 5 },
    ],
    Trips: [
      {
        Id: 1,
        SeroPackageId: 1001,
        TripPathId: 1,
        TripPath: 'Jeddah Airport to Makkah',
        CarTypeId: 1,
        CarType: 'Bus 49 Seats',
        VehiclesCount: 1,
        Price: 720,
      },
      {
        Id: 2,
        SeroPackageId: 1001,
        TripPathId: 2,
        TripPath: 'Makkah to Madinah',
        CarTypeId: 1,
        CarType: 'Bus 49 Seats',
        VehiclesCount: 1,
        Price: 840,
      },
    ],
    Caterings: [
      {
        Id: 1,
        SeroPackageId: 1001,
        CateringTypeId: 1,
        CateringType: 'Breakfast',
        FoodTypeId: 1,
        FoodType: 'Open Buffet',
        Count: 45,
        Price: 540,
      },
    ],
    Tickets: [
      {
        Id: 1,
        SeroPackageId: 1001,
        SourceCountryID: 2,
        SourceCountryName: 'Egypt',
        SourceCityID: 4,
        SourceCityName: 'Cairo',
        DestinationCountryID: 1,
        DestinationCountryName: 'Saudi Arabia',
        DestinationCityID: 1,
        DestinationCityName: 'Jeddah',
        AirlineCompanyID: 1,
        AirlineCompanyNameEn: 'Saudia',
        AirlineCompanyNameAr: 'Saudia',
        SeatCount: 45,
        TripType: 'RoundTrip',
        TravelClass: 'Economy',
        Price: 52200,
      },
    ],
    Agents: [
      { Id: 1, SeroPackageId: 1001, AgentId: 301, AgentName: 'Al Safa Travel', AgentCountry: 'Egypt', AgentCity: 'Cairo', IsActive: true },
      { Id: 2, SeroPackageId: 1001, AgentId: 302, AgentName: 'Nour Tours', AgentCountry: 'Saudi Arabia', AgentCity: 'Riyadh', IsActive: true },
    ],
    Tags: [mockPackageTags[0], mockPackageTags[1]],
  },
  {
    PackageID: 1002,
    PackageCode: 'PKG-2026-002',
    Title: 'Economy Umrah Package',
    Price: 3980,
    VerifiedPrice: false,
    BlendedPrice: true,
    StartDate: new Date('2026-07-10'),
    EndDate: new Date('2026-07-18'),
    IsVisaIncluded: false,
    IsActive: true,
    IsByAgent: true,
    ImageUrl: null,
    GuestCount: 30,
    Quantity: 20,
    AddedDate: new Date('2026-05-06T09:00:00'),
    AddedBy: 'Prototype Admin',
    Hotels: [
      {
        Id: 3,
        SeroPackageId: 1002,
        CityId: 1,
        CityName: 'Makkah',
        DistrictId: 12,
        DistrictName: 'Al Aziziyah',
        HotelStar: 4,
        HotelCategoryID: 2,
        HotelCategoryName: 'Four Star',
        RoomTypeID: 2,
        RoomTypeName: 'Triple Room',
        NightsCount: 4,
        RoomCount: 8,
        Price: 1600,
      },
      {
        Id: 4,
        SeroPackageId: 1002,
        CityId: 2,
        CityName: 'Madinah',
        DistrictId: 22,
        DistrictName: 'Qurban',
        HotelStar: 4,
        HotelCategoryID: 2,
        HotelCategoryName: 'Four Star',
        RoomTypeID: 2,
        RoomTypeName: 'Triple Room',
        NightsCount: 4,
        RoomCount: 8,
        Price: 1280,
      },
    ],
    HotelCounts: [
      { Id: 3, SeroPackageId: 1002, CityId: 1, CityName: 'Makkah', NightCount: 4 },
      { Id: 4, SeroPackageId: 1002, CityId: 2, CityName: 'Madinah', NightCount: 4 },
    ],
    Trips: [
      { Id: 3, SeroPackageId: 1002, TripPathId: 3, TripPath: 'Madinah to Jeddah Airport', CarTypeId: 2, CarType: 'Coaster 22 Seats', VehiclesCount: 2, Price: 900 },
    ],
    Caterings: [
      { Id: 2, SeroPackageId: 1002, CateringTypeId: 2, CateringType: 'Dinner', FoodTypeId: 2, FoodType: 'Box Meal', Count: 30, Price: 330 },
    ],
    Tickets: [],
    Agents: [
      { Id: 3, SeroPackageId: 1002, AgentId: 303, AgentName: 'Umrah Gate', AgentCountry: 'Jordan', AgentCity: 'Amman', IsActive: true },
    ],
    Tags: [mockPackageTags[2]],
  },
  {
    PackageID: 1003,
    PackageCode: 'PKG-2026-003',
    Title: 'Ramadan Express Package',
    Price: 6150,
    VerifiedPrice: true,
    BlendedPrice: false,
    StartDate: new Date('2027-02-12'),
    EndDate: new Date('2027-02-20'),
    IsVisaIncluded: true,
    IsActive: false,
    IsByAgent: false,
    ImageUrl: null,
    GuestCount: 25,
    Quantity: 8,
    AddedDate: new Date('2026-05-08T12:15:00'),
    AddedBy: 'Prototype Admin',
    Hotels: [],
    HotelCounts: [],
    Trips: [],
    Caterings: [],
    Tickets: [],
    Agents: [],
    Tags: [mockPackageTags[3]],
  },
];
