import { Injectable } from '@angular/core';
import { Agent } from '../models';
import { UserRole } from '../models/enums';

@Injectable({ providedIn: 'root' })
export class MockDataService {

  readonly agents: Agent[] = [
    {
      id: 'admin-001',
      name: 'TARIQ AMER',
      companyName: 'Umrah Platform Admin',
      email: 'admin@umrahplatform.com',
      phone: '+966501234567',
      country: 'Saudi Arabia',
      city: 'Riyadh',
      role: UserRole.ADMIN,
      isVerified: true,
      isActive: true,
      joinedAt: new Date('2022-01-01'),
      lastActiveAt: new Date(),
      totalSales: 0,
      totalRevenue: 0,
      pendingBalance: 0,
      commissionRate: 0
    },
    {
      id: 'master-001',
      name: 'Abdullah Al-Noor',
      companyName: 'Al Noor Travel & Tourism',
      email: 'abdullahalnoor@alnoortravel.com',
      phone: '+966551234567',
      country: 'Saudi Arabia',
      city: 'Jeddah',
      role: UserRole.MASTER_AGENT,
      isVerified: true,
      isActive: true,
      subagentIds: ['agent-001', 'agent-002', 'agent-003'],
      joinedAt: new Date('2022-03-15'),
      lastActiveAt: new Date(),
      totalSales: 248,
      totalRevenue: 1240000,
      pendingBalance: 42000,
      commissionRate: 8,
      licenseNumber: 'SA-TA-20221847'
    },
    {
      id: 'master-002',
      name: 'Khalid Al-Zamil',
      companyName: 'Zamil Tourism Group',
      email: 'khalid@zamiltourism.com',
      phone: '+966501112233',
      country: 'Saudi Arabia',
      city: 'Riyadh',
      role: UserRole.MASTER_AGENT,
      isVerified: true,
      isActive: true,
      subagentIds: ['agent-004', 'agent-005'],
      joinedAt: new Date('2022-06-10'),
      lastActiveAt: new Date(),
      totalSales: 185,
      totalRevenue: 925000,
      pendingBalance: 18500,
      commissionRate: 7,
      licenseNumber: 'SA-TA-20224519'
    },
    {
      id: 'agent-001',
      name: 'Tariq Hassan',
      companyName: 'Hassan Travel Agency',
      email: 'tariq@hassantravel.com',
      phone: '+966509876543',
      country: 'Saudi Arabia',
      city: 'Makkah',
      role: UserRole.SUB_AGENT,
      isVerified: true,
      isActive: true,
      masterAgentId: 'master-001',
      joinedAt: new Date('2022-05-20'),
      lastActiveAt: new Date(),
      totalSales: 64,
      totalRevenue: 320000,
      pendingBalance: 12000,
      commissionRate: 5
    },
    {
      id: 'agent-002',
      name: 'Yusuf Badr',
      companyName: 'Badr Pilgrim Services',
      email: 'yusuf@badrpilgrim.com',
      phone: '+966508765432',
      country: 'Saudi Arabia',
      city: 'Madinah',
      role: UserRole.SUB_AGENT,
      isVerified: true,
      isActive: true,
      masterAgentId: 'master-001',
      joinedAt: new Date('2022-07-12'),
      lastActiveAt: new Date(),
      totalSales: 48,
      totalRevenue: 240000,
      pendingBalance: 9600,
      commissionRate: 5
    },
    {
      id: 'agent-003',
      name: 'Ibrahim Qureshi',
      companyName: 'Qureshi Umrah Services',
      email: 'ibrahim@qureshitravel.com',
      phone: '+923001234567',
      country: 'Pakistan',
      city: 'Lahore',
      role: UserRole.SUB_AGENT,
      isVerified: false,
      isActive: true,
      masterAgentId: 'master-001',
      joinedAt: new Date('2023-01-05'),
      lastActiveAt: new Date(),
      totalSales: 22,
      totalRevenue: 110000,
      pendingBalance: 4400,
      commissionRate: 4
    },
    {
      id: 'agent-004',
      name: 'Amr Mostafa',
      companyName: 'Mostafa Hajj & Umrah',
      email: 'amr@mostafaftravel.com',
      phone: '+201012345678',
      country: 'Egypt',
      city: 'Cairo',
      role: UserRole.SUB_AGENT,
      isVerified: true,
      isActive: true,
      masterAgentId: 'master-002',
      joinedAt: new Date('2022-09-01'),
      lastActiveAt: new Date(),
      totalSales: 91,
      totalRevenue: 455000,
      pendingBalance: 18200,
      commissionRate: 5
    },
    {
      id: 'agent-005',
      name: 'Bilal Chaudhry',
      companyName: 'Chaudhry Travel & Tours',
      email: 'bilal@chaudhrytravel.pk',
      phone: '+923214567890',
      country: 'Pakistan',
      city: 'Karachi',
      role: UserRole.SUB_AGENT,
      isVerified: true,
      isActive: true,
      masterAgentId: 'master-002',
      joinedAt: new Date('2023-02-18'),
      lastActiveAt: new Date(),
      totalSales: 55,
      totalRevenue: 275000,
      pendingBalance: 11000,
      commissionRate: 4.5
    }
  ];

  getAgentById(id: string): Agent | undefined {
    return this.agents.find(a => a.id === id);
  }
}
