// Currently using local mock data for frontend prototype. Later this can be replaced with backend API.

import { RequestModel, SeroPackageModel } from 'src/app/services/admin.api.client';

export const MOCK_PACKAGES: SeroPackageModel[] = [
  {
    PackageID: 1,
    PackageCode: 'PKG-001',
    Title: 'Premium Umrah Package – Makkah & Madinah',
    Description: 'Complete 14-day Umrah experience with luxury hotels',
    Price: 8500,
    VerifiedPrice: true,
    BlendedPrice: false,
    StartDate: new Date('2026-06-01') as any,
    EndDate: new Date('2026-06-14') as any,
    IsVisaIncluded: true,
    IsActive: true,
    GuestCount: 4,
    Quantity: 20,
    ImageUrl: null,
    Tags: [{ TagID: 1, Name: 'Luxury', Color: '#8c7b3d' }, { TagID: 2, Name: 'Family', Color: '#3d7a52' }],
    Hotels: [
      { Id: 1, CityId: 1, CityName: 'Makkah', HotelName: 'Hilton Suites Makkah', HotelStar: 5, NightsCount: 7, RoomCount: 2, Price: 3500 },
      { Id: 2, CityId: 2, CityName: 'Madinah', HotelName: 'Anwar Al Madinah Movenpick', HotelStar: 5, NightsCount: 5, RoomCount: 2, Price: 2000 },
    ],
    HotelCounts: [
      { Id: 1, CityId: 1, CityName: 'Makkah', NightCount: 7 },
      { Id: 2, CityId: 2, CityName: 'Madinah', NightCount: 5 },
    ],
    Trips: [
      { Id: 1, TripPath: 'Jeddah Airport → Makkah', CarType: 'VIP Bus', VehiclesCount: 1, Price: 400 },
      { Id: 2, TripPath: 'Makkah → Madinah', CarType: 'VIP Bus', VehiclesCount: 1, Price: 350 },
    ],
    Tickets: [
      { Id: 1, SourceCityName: 'Cairo', DestinationCityName: 'Jeddah', AirlineCompanyNameEn: 'EgyptAir', SeatCount: 4, TripType: 'Round Trip', TravelClass: 'Economy', Price: 1200 },
    ],
    Caterings: [
      { Id: 1, CateringType: 'Daily Meals', FoodType: 'Saudi Cuisine', Count: 14, Price: 700 },
    ],
  },
  {
    PackageID: 2,
    PackageCode: 'PKG-002',
    Title: 'Economy Umrah Package – 10 Days',
    Description: '10-day budget-friendly Umrah package',
    Price: 4200,
    VerifiedPrice: false,
    BlendedPrice: true,
    StartDate: new Date('2026-07-05') as any,
    EndDate: new Date('2026-07-14') as any,
    IsVisaIncluded: false,
    IsActive: true,
    GuestCount: 2,
    Quantity: 50,
    ImageUrl: null,
    Tags: [{ TagID: 3, Name: 'Budget', Color: '#3a472a' }, { TagID: 4, Name: 'Standard', Color: '#74806a' }],
    Hotels: [
      { Id: 3, CityId: 1, CityName: 'Makkah', HotelName: 'Al Naseem Hotel', HotelStar: 3, NightsCount: 6, RoomCount: 1, Price: 900 },
      { Id: 4, CityId: 2, CityName: 'Madinah', HotelName: 'Dallah Taibah', HotelStar: 3, NightsCount: 4, RoomCount: 1, Price: 600 },
    ],
    HotelCounts: [
      { Id: 3, CityId: 1, CityName: 'Makkah', NightCount: 6 },
      { Id: 4, CityId: 2, CityName: 'Madinah', NightCount: 4 },
    ],
    Trips: [
      { Id: 3, TripPath: 'Jeddah Airport → Makkah', CarType: 'Standard Bus', VehiclesCount: 1, Price: 150 },
    ],
    Tickets: [],
    Caterings: [],
  },
  {
    PackageID: 3,
    PackageCode: 'PKG-003',
    Title: 'VIP Ramadan Umrah – Full Board',
    Description: 'Exclusive Ramadan Umrah with full-board meals',
    Price: 15000,
    VerifiedPrice: true,
    BlendedPrice: true,
    StartDate: new Date('2026-03-10') as any,
    EndDate: new Date('2026-03-27') as any,
    IsVisaIncluded: true,
    IsActive: true,
    GuestCount: 2,
    Quantity: 10,
    ImageUrl: null,
    Tags: [{ TagID: 5, Name: 'VIP', Color: '#8c7b3d' }, { TagID: 6, Name: 'Ramadan', Color: '#3d7a52' }],
    Hotels: [
      { Id: 5, CityId: 1, CityName: 'Makkah', HotelName: 'Makkah Clock Tower – Fairmont', HotelStar: 5, NightsCount: 12, RoomCount: 1, Price: 8000 },
      { Id: 6, CityId: 2, CityName: 'Madinah', HotelName: 'Al Ansar Grand Hotel', HotelStar: 5, NightsCount: 5, RoomCount: 1, Price: 2500 },
    ],
    HotelCounts: [
      { Id: 5, CityId: 1, CityName: 'Makkah', NightCount: 12 },
      { Id: 6, CityId: 2, CityName: 'Madinah', NightCount: 5 },
    ],
    Trips: [
      { Id: 4, TripPath: 'Jeddah Airport → Makkah', CarType: 'VIP Limousine', VehiclesCount: 1, Price: 800 },
      { Id: 5, TripPath: 'Makkah → Madinah', CarType: 'VIP Bus', VehiclesCount: 1, Price: 600 },
    ],
    Tickets: [
      { Id: 2, SourceCityName: 'Dubai', DestinationCityName: 'Jeddah', AirlineCompanyNameEn: 'Emirates', SeatCount: 2, TripType: 'Round Trip', TravelClass: 'Business', Price: 3000 },
    ],
    Caterings: [
      { Id: 2, CateringType: 'Full Board', FoodType: 'Mixed Cuisine', Count: 17, Price: 2500 },
    ],
  },
  {
    PackageID: 4,
    PackageCode: 'PKG-004',
    Title: 'Group Umrah Package – 15 Persons',
    Description: '7-day group Umrah with dedicated guide',
    Price: 3800,
    VerifiedPrice: true,
    BlendedPrice: false,
    StartDate: new Date('2026-08-01') as any,
    EndDate: new Date('2026-08-07') as any,
    IsVisaIncluded: true,
    IsActive: true,
    GuestCount: 15,
    Quantity: 5,
    ImageUrl: null,
    Tags: [{ TagID: 7, Name: 'Group', Color: '#3a472a' }],
    Hotels: [
      { Id: 7, CityId: 1, CityName: 'Makkah', HotelName: 'Swissôtel Makkah', HotelStar: 4, NightsCount: 4, RoomCount: 6, Price: 2400 },
      { Id: 8, CityId: 2, CityName: 'Madinah', HotelName: 'Oberoi Madinah', HotelStar: 4, NightsCount: 3, RoomCount: 6, Price: 1800 },
    ],
    HotelCounts: [
      { Id: 7, CityId: 1, CityName: 'Makkah', NightCount: 4 },
      { Id: 8, CityId: 2, CityName: 'Madinah', NightCount: 3 },
    ],
    Trips: [
      { Id: 6, TripPath: 'Madinah Airport → Madinah City', CarType: 'Coach', VehiclesCount: 1, Price: 300 },
      { Id: 7, TripPath: 'Madinah → Makkah', CarType: 'Coach', VehiclesCount: 1, Price: 400 },
    ],
    Tickets: [],
    Caterings: [
      { Id: 3, CateringType: 'Breakfast', FoodType: 'Arabic Breakfast', Count: 7, Price: 500 },
    ],
  },
  {
    PackageID: 5,
    PackageCode: 'PKG-005',
    Title: 'Family Umrah + Taif Trip',
    Description: '12-day Umrah with scenic Taif day trip',
    Price: 7200,
    VerifiedPrice: false,
    BlendedPrice: false,
    StartDate: new Date('2026-09-15') as any,
    EndDate: new Date('2026-09-26') as any,
    IsVisaIncluded: true,
    IsActive: true,
    GuestCount: 6,
    Quantity: 8,
    ImageUrl: null,
    Tags: [{ TagID: 8, Name: 'Family', Color: '#3d7a52' }, { TagID: 9, Name: 'Tour', Color: '#8c7b3d' }],
    Hotels: [
      { Id: 9, CityId: 1, CityName: 'Makkah', HotelName: 'Le Meridien Towers', HotelStar: 4, NightsCount: 7, RoomCount: 2, Price: 2800 },
      { Id: 10, CityId: 2, CityName: 'Madinah', HotelName: 'Pullman Zamzam', HotelStar: 4, NightsCount: 5, RoomCount: 2, Price: 2000 },
    ],
    HotelCounts: [
      { Id: 9, CityId: 1, CityName: 'Makkah', NightCount: 7 },
      { Id: 10, CityId: 2, CityName: 'Madinah', NightCount: 5 },
    ],
    Trips: [
      { Id: 8, TripPath: 'Jeddah Airport → Makkah', CarType: 'VIP Bus', VehiclesCount: 1, Price: 350 },
      { Id: 9, TripPath: 'Makkah → Taif (Day Trip)', CarType: 'Private Car', VehiclesCount: 2, Price: 600 },
    ],
    Tickets: [
      { Id: 3, SourceCityName: 'Istanbul', DestinationCityName: 'Jeddah', AirlineCompanyNameEn: 'Turkish Airlines', SeatCount: 6, TripType: 'Round Trip', TravelClass: 'Economy', Price: 1800 },
    ],
    Caterings: [
      { Id: 4, CateringType: 'Dinner', FoodType: 'Turkish Cuisine', Count: 12, Price: 900 },
    ],
  },
  {
    PackageID: 6,
    PackageCode: 'PKG-006',
    Title: 'Silver Umrah – 8 Days',
    Description: 'Comfortable 8-day Umrah for individual travelers',
    Price: 5100,
    VerifiedPrice: true,
    BlendedPrice: false,
    StartDate: new Date('2026-10-01') as any,
    EndDate: new Date('2026-10-08') as any,
    IsVisaIncluded: false,
    IsActive: true,
    GuestCount: 1,
    Quantity: 30,
    ImageUrl: null,
    Tags: [{ TagID: 10, Name: 'Solo', Color: '#74806a' }],
    Hotels: [
      { Id: 11, CityId: 1, CityName: 'Makkah', HotelName: 'Jabal Omar Hyatt', HotelStar: 5, NightsCount: 5, RoomCount: 1, Price: 2500 },
      { Id: 12, CityId: 2, CityName: 'Madinah', HotelName: 'Dar Al Iman', HotelStar: 4, NightsCount: 3, RoomCount: 1, Price: 900 },
    ],
    HotelCounts: [
      { Id: 11, CityId: 1, CityName: 'Makkah', NightCount: 5 },
      { Id: 12, CityId: 2, CityName: 'Madinah', NightCount: 3 },
    ],
    Trips: [
      { Id: 10, TripPath: 'Jeddah → Makkah → Madinah → Jeddah', CarType: 'Shared Bus', VehiclesCount: 1, Price: 250 },
    ],
    Tickets: [],
    Caterings: [],
  },
];

export interface RequestModelLocal {
  Id: number;
  SeroPackageId: number;
  AgentId: number;
  AgentCode: string | null;
  AgentName: string | null;
  AgentCountry: string | null;
  StatusId: number;
  StatusName: string | null;
  StartDate: Date;
  EndDate: Date;
  PassengerCount: number;
  RequestedQuantity: number;
  Notes: string | null;
  AddedDate: Date;
  IsByAgent: boolean;
  PackageCode: string | null;
  Title: string | null;
  Price: number;
}

export let MOCK_REQUESTS: RequestModelLocal[] = [
  {
    Id: 1001,
    SeroPackageId: 1,
    AgentId: 101,
    AgentCode: 'AGT-001',
    AgentName: 'النسر للسياحة والسفر',
    AgentCountry: 'Saudi Arabia',
    StatusId: 2,
    StatusName: 'new',
    StartDate: new Date('2026-07-01'),
    EndDate: new Date('2026-07-14'),
    PassengerCount: 10,
    RequestedQuantity: 1,
    Notes: 'Please arrange VIP transfers',
    AddedDate: new Date('2026-05-10'),
    IsByAgent: true,
    PackageCode: 'PKG-001',
    Title: 'Premium Umrah Package – Makkah & Madinah',
    Price: 8500,
  },
  {
    Id: 1002,
    SeroPackageId: 2,
    AgentId: 102,
    AgentCode: 'AGT-002',
    AgentName: 'Al Noor Travel Agency',
    AgentCountry: 'Egypt',
    StatusId: 1,
    StatusName: 'pending',
    StartDate: new Date('2026-08-05'),
    EndDate: new Date('2026-08-14'),
    PassengerCount: 25,
    RequestedQuantity: 2,
    Notes: '',
    AddedDate: new Date('2026-05-12'),
    IsByAgent: true,
    PackageCode: 'PKG-002',
    Title: 'Economy Umrah Package – 10 Days',
    Price: 4200,
  },
  {
    Id: 1003,
    SeroPackageId: 3,
    AgentId: 103,
    AgentCode: 'AGT-003',
    AgentName: 'Star Tourism Turkey',
    AgentCountry: 'Turkey',
    StatusId: 3,
    StatusName: 'approved',
    StartDate: new Date('2026-03-15'),
    EndDate: new Date('2026-03-27'),
    PassengerCount: 2,
    RequestedQuantity: 1,
    Notes: 'Business class tickets required',
    AddedDate: new Date('2026-05-01'),
    IsByAgent: true,
    PackageCode: 'PKG-003',
    Title: 'VIP Ramadan Umrah – Full Board',
    Price: 15000,
  },
  {
    Id: 1004,
    SeroPackageId: 4,
    AgentId: 101,
    AgentCode: 'AGT-001',
    AgentName: 'النسر للسياحة والسفر',
    AgentCountry: 'Saudi Arabia',
    StatusId: 4,
    StatusName: 'rejected',
    StartDate: new Date('2026-09-01'),
    EndDate: new Date('2026-09-07'),
    PassengerCount: 15,
    RequestedQuantity: 1,
    Notes: 'Group booking',
    AddedDate: new Date('2026-04-20'),
    IsByAgent: true,
    PackageCode: 'PKG-004',
    Title: 'Group Umrah Package – 15 Persons',
    Price: 3800,
  },
  {
    Id: 1005,
    SeroPackageId: 5,
    AgentId: 104,
    AgentCode: 'AGT-004',
    AgentName: 'Crescent Travels',
    AgentCountry: 'Jordan',
    StatusId: 5,
    StatusName: 'completed',
    StartDate: new Date('2026-09-15'),
    EndDate: new Date('2026-09-26'),
    PassengerCount: 6,
    RequestedQuantity: 1,
    Notes: 'Family package with kids',
    AddedDate: new Date('2026-04-15'),
    IsByAgent: true,
    PackageCode: 'PKG-005',
    Title: 'Family Umrah + Taif Trip',
    Price: 7200,
  },
  {
    Id: 1006,
    SeroPackageId: 6,
    AgentId: 105,
    AgentCode: 'AGT-005',
    AgentName: 'Golden Gate Tours',
    AgentCountry: 'UAE',
    StatusId: 1,
    StatusName: 'pending',
    StartDate: new Date('2026-10-10'),
    EndDate: new Date('2026-10-17'),
    PassengerCount: 3,
    RequestedQuantity: 3,
    Notes: '',
    AddedDate: new Date('2026-05-14'),
    IsByAgent: true,
    PackageCode: 'PKG-006',
    Title: 'Silver Umrah – 8 Days',
    Price: 5100,
  },
  {
    Id: 1007,
    SeroPackageId: 1,
    AgentId: 102,
    AgentCode: 'AGT-002',
    AgentName: 'Al Noor Travel Agency',
    AgentCountry: 'Egypt',
    StatusId: 2,
    StatusName: 'new',
    StartDate: new Date('2026-11-01'),
    EndDate: new Date('2026-11-14'),
    PassengerCount: 8,
    RequestedQuantity: 2,
    Notes: 'Need special dietary requirements',
    AddedDate: new Date('2026-05-15'),
    IsByAgent: true,
    PackageCode: 'PKG-001',
    Title: 'Premium Umrah Package – Makkah & Madinah',
    Price: 8500,
  },
];
