// Currently using local mock data for frontend prototype. Later this can be replaced with backend API.
import {
  RequestModel, RequestVoucherModel, VoucherDetailsModel,
  VoucherStatusLogModel,
} from './orders.model';

export const MOCK_ORDERS: RequestModel[] = [
  {
    Id: 1001,
    SeroPackageId: 201,
    AgentId: 10,
    AgentCode: 'AGT-001',
    AgentName: 'Ahmed Al-Rashidi',
    StatusId: 1,
    StatusName: 'approved',
    StartDate: '2025-03-10',
    EndDate: '2025-03-20',
    PassengerCount: 20,
    RequestedQuantity: 2,
    Notes: 'VIP group, needs special accommodation',
    AddedDate: '2025-02-15T09:30:00',
    IsByAgent: true,
    PackageCode: 'PKG-2025-001',
    Title: 'Full Umrah Package - Premium',
    Price: 4500,
    PackageModel: {
      PackageID: 201,
      Title: 'Full Umrah Package - Premium',
      PackageCode: 'PKG-2025-001',
      StartDate: '2025-03-01',
      EndDate: '2025-04-30',
      Price: 4500,
      GuestCount: 10,
      ImageUrl: '',
      VisaIncluded: true,
      HotelCount: 2,
      TransportCount: 1,
      TicketCount: 1,
      CateringCount: 1,
    },
  },
  {
    Id: 1002,
    SeroPackageId: 202,
    AgentId: 10,
    AgentCode: 'AGT-001',
    AgentName: 'Ahmed Al-Rashidi',
    StatusId: 2,
    StatusName: 'pending',
    StartDate: '2025-04-05',
    EndDate: '2025-04-15',
    PassengerCount: 10,
    RequestedQuantity: 1,
    Notes: '',
    AddedDate: '2025-03-01T11:00:00',
    IsByAgent: true,
    PackageCode: 'PKG-2025-002',
    Title: 'Economy Umrah Package',
    Price: 2200,
    PackageModel: {
      PackageID: 202,
      Title: 'Economy Umrah Package',
      PackageCode: 'PKG-2025-002',
      StartDate: '2025-04-01',
      EndDate: '2025-05-31',
      Price: 2200,
      GuestCount: 10,
      ImageUrl: '',
      VisaIncluded: false,
      HotelCount: 1,
      TransportCount: 1,
      TicketCount: 0,
      CateringCount: 0,
    },
  },
  {
    Id: 1003,
    SeroPackageId: 203,
    AgentId: 10,
    AgentCode: 'AGT-001',
    AgentName: 'Ahmed Al-Rashidi',
    StatusId: 3,
    StatusName: 'rejected',
    StartDate: '2025-05-01',
    EndDate: '2025-05-10',
    PassengerCount: 15,
    RequestedQuantity: 1,
    Notes: 'Budget exceeded',
    AddedDate: '2025-04-01T08:00:00',
    IsByAgent: false,
    PackageCode: 'PKG-2025-003',
    Title: 'Standard Umrah + Ziyarat',
    Price: 3100,
    PackageModel: {
      PackageID: 203,
      Title: 'Standard Umrah + Ziyarat',
      PackageCode: 'PKG-2025-003',
      StartDate: '2025-05-01',
      EndDate: '2025-06-30',
      Price: 3100,
      GuestCount: 15,
      ImageUrl: '',
      VisaIncluded: true,
      HotelCount: 2,
      TransportCount: 2,
      TicketCount: 1,
      CateringCount: 2,
    },
  },
  {
    Id: 1004,
    SeroPackageId: 204,
    AgentId: 10,
    AgentCode: 'AGT-001',
    AgentName: 'Ahmed Al-Rashidi',
    StatusId: 4,
    StatusName: 'new',
    StartDate: '2025-06-10',
    EndDate: '2025-06-20',
    PassengerCount: 8,
    RequestedQuantity: 1,
    Notes: 'Family group',
    AddedDate: '2025-05-20T14:00:00',
    IsByAgent: true,
    PackageCode: 'PKG-2025-004',
    Title: 'Family Umrah Package',
    Price: 1800,
    PackageModel: {
      PackageID: 204,
      Title: 'Family Umrah Package',
      PackageCode: 'PKG-2025-004',
      StartDate: '2025-06-01',
      EndDate: '2025-07-31',
      Price: 1800,
      GuestCount: 8,
      ImageUrl: '',
      VisaIncluded: true,
      HotelCount: 1,
      TransportCount: 1,
      TicketCount: 1,
      CateringCount: 0,
    },
  },
  {
    Id: 1005,
    SeroPackageId: 205,
    AgentId: 10,
    AgentCode: 'AGT-001',
    AgentName: 'Ahmed Al-Rashidi',
    StatusId: 5,
    StatusName: 'completed',
    StartDate: '2025-01-10',
    EndDate: '2025-01-20',
    PassengerCount: 25,
    RequestedQuantity: 3,
    Notes: 'Completed successfully',
    AddedDate: '2024-12-01T10:00:00',
    IsByAgent: true,
    PackageCode: 'PKG-2024-010',
    Title: 'Luxury Umrah Experience',
    Price: 7500,
    PackageModel: {
      PackageID: 205,
      Title: 'Luxury Umrah Experience',
      PackageCode: 'PKG-2024-010',
      StartDate: '2025-01-01',
      EndDate: '2025-02-28',
      Price: 7500,
      GuestCount: 25,
      ImageUrl: '',
      VisaIncluded: true,
      HotelCount: 3,
      TransportCount: 2,
      TicketCount: 2,
      CateringCount: 3,
    },
  },
];

export const MOCK_VOUCHERS: Record<number, RequestVoucherModel[]> = {
  1001: [
    {
      RequestVoucherID: 5001,
      RequestVoucherCode: 'VCH-5001',
      SeroPackageRequestID: 1001,
      RequestVoucherTypeID: 1,
      VoucherStatusForAgentID: 1,
      VoucherStatusForAdminID: 2,
      VoucherStatusForAgentTitle: 'Confirmed',
      VoucherStatusForAdminTitle: 'Pending Approval',
      TotalCostPrice: 1800,
      TotalOriginalPrice: 2000,
      TotalSellingPrice: 2200,
      TotalTax: 110,
      TotalPriceWithTax: 2310,
      AddedDate: '2025-02-16T10:00:00',
      AgentID: 10,
    },
    {
      RequestVoucherID: 5002,
      RequestVoucherCode: 'VCH-5002',
      SeroPackageRequestID: 1001,
      RequestVoucherTypeID: 3,
      VoucherStatusForAgentID: 1,
      VoucherStatusForAdminID: 1,
      VoucherStatusForAgentTitle: 'Confirmed',
      VoucherStatusForAdminTitle: 'Approved',
      TotalCostPrice: 500,
      TotalOriginalPrice: 600,
      TotalSellingPrice: 650,
      TotalTax: 32,
      TotalPriceWithTax: 682,
      AddedDate: '2025-02-16T10:05:00',
      AgentID: 10,
    },
    {
      RequestVoucherID: 5003,
      RequestVoucherCode: 'VCH-5003',
      SeroPackageRequestID: 1001,
      RequestVoucherTypeID: 2,
      VoucherStatusForAgentID: 1,
      VoucherStatusForAdminID: 1,
      VoucherStatusForAgentTitle: 'Confirmed',
      VoucherStatusForAdminTitle: 'Approved',
      TotalCostPrice: 900,
      TotalOriginalPrice: 1000,
      TotalSellingPrice: 1100,
      TotalTax: 55,
      TotalPriceWithTax: 1155,
      AddedDate: '2025-02-16T10:10:00',
      AgentID: 10,
    },
  ],
  1002: [
    {
      RequestVoucherID: 5004,
      RequestVoucherCode: 'VCH-5004',
      SeroPackageRequestID: 1002,
      RequestVoucherTypeID: 1,
      VoucherStatusForAgentID: 2,
      VoucherStatusForAdminID: 2,
      VoucherStatusForAgentTitle: 'Pending',
      VoucherStatusForAdminTitle: 'Pending Approval',
      TotalCostPrice: 900,
      TotalOriginalPrice: 1000,
      TotalSellingPrice: 1100,
      TotalTax: 55,
      TotalPriceWithTax: 1155,
      AddedDate: '2025-03-02T09:00:00',
      AgentID: 10,
    },
  ],
  1003: [
    {
      RequestVoucherID: 5005,
      RequestVoucherCode: 'VCH-5005',
      SeroPackageRequestID: 1003,
      RequestVoucherTypeID: 4,
      VoucherStatusForAgentID: 3,
      VoucherStatusForAdminID: 10,
      VoucherStatusForAgentTitle: 'Rejected',
      VoucherStatusForAdminTitle: 'Rejected',
      TotalCostPrice: 400,
      TotalOriginalPrice: 480,
      TotalSellingPrice: 520,
      TotalTax: 26,
      TotalPriceWithTax: 546,
      AddedDate: '2025-04-02T08:30:00',
      AgentID: 10,
    },
  ],
  1004: [],
  1005: [
    {
      RequestVoucherID: 5006,
      RequestVoucherCode: 'VCH-5006',
      SeroPackageRequestID: 1005,
      RequestVoucherTypeID: 5,
      VoucherStatusForAgentID: 1,
      VoucherStatusForAdminID: 1,
      VoucherStatusForAgentTitle: 'Confirmed',
      VoucherStatusForAdminTitle: 'Approved',
      TotalCostPrice: 2500,
      TotalOriginalPrice: 3000,
      TotalSellingPrice: 3300,
      TotalTax: 165,
      TotalPriceWithTax: 3465,
      AddedDate: '2024-12-02T10:00:00',
      AgentID: 10,
    },
    {
      RequestVoucherID: 5007,
      RequestVoucherCode: 'VCH-5007',
      SeroPackageRequestID: 1005,
      RequestVoucherTypeID: 1,
      VoucherStatusForAgentID: 1,
      VoucherStatusForAdminID: 1,
      VoucherStatusForAgentTitle: 'Confirmed',
      VoucherStatusForAdminTitle: 'Approved',
      TotalCostPrice: 3000,
      TotalOriginalPrice: 3500,
      TotalSellingPrice: 3800,
      TotalTax: 190,
      TotalPriceWithTax: 3990,
      AddedDate: '2024-12-02T10:15:00',
      AgentID: 10,
    },
  ],
};

export const MOCK_VOUCHER_DETAILS: Record<number, VoucherDetailsModel> = {
  5001: {
    Voucher: MOCK_VOUCHERS[1001][0],
    HotelVouchers: [
      {
        RequestHotelVoucherDetailID: 1,
        RequestVoucherID: 5001,
        HotelID: 101,
        HotelName: 'Makkah Grand Hotel',
        RoomTypeID: 1,
        RoomTypeTitle: 'Double Room',
        RoomCount: 10,
        StartDate: '2025-03-10',
        EndDate: '2025-03-15',
        NightsCount: 5,
        UnitCostPrice: 180,
        UnitOriginalPrice: 200,
        UnitSellingPrice: 220,
        UnitTax: 11,
        UnitPriceWithTax: 231,
        TotalCostPrice: 1800,
        TotalOriginalPrice: 2000,
        TotalSellingPrice: 2200,
        TotalTax: 110,
        TotalPriceWithTax: 2310,
      },
    ],
    VisaVouchers: [],
    CateringVouchers: [],
    TripVouchers: [],
    TicketVouchers: [],
  },
  5002: {
    Voucher: MOCK_VOUCHERS[1001][1],
    HotelVouchers: [],
    VisaVouchers: [
      {
        RequestVisaVoucherDetailID: 1,
        RequestVoucherID: 5002,
        Count: 20,
        UnitCostPrice: 25,
        UnitOriginalPrice: 30,
        UnitSellingPrice: 32.5,
        UnitTax: 1.6,
        UnitPriceWithTax: 34.1,
        TotalCostPrice: 500,
        TotalOriginalPrice: 600,
        TotalSellingPrice: 650,
        TotalTax: 32,
        TotalPriceWithTax: 682,
      },
    ],
    CateringVouchers: [],
    TripVouchers: [],
    TicketVouchers: [],
  },
  5003: {
    Voucher: MOCK_VOUCHERS[1001][2],
    HotelVouchers: [],
    VisaVouchers: [],
    CateringVouchers: [],
    TripVouchers: [
      {
        RequestTripVoucherDetailID: 1,
        RequestVoucherID: 5003,
        TripPathID: 1,
        TripPathTitle: 'Makkah - Madinah - Makkah',
        CarTypeID: 2,
        CarTypeTitle: 'Van (15 seats)',
        Count: 2,
        UnitCostPrice: 450,
        UnitOriginalPrice: 500,
        UnitSellingPrice: 550,
        UnitTax: 27.5,
        UnitPriceWithTax: 577.5,
        TotalCostPrice: 900,
        TotalOriginalPrice: 1000,
        TotalSellingPrice: 1100,
        TotalTax: 55,
        TotalPriceWithTax: 1155,
      },
    ],
    TicketVouchers: [],
  },
  5004: {
    Voucher: MOCK_VOUCHERS[1002][0],
    HotelVouchers: [
      {
        RequestHotelVoucherDetailID: 2,
        RequestVoucherID: 5004,
        HotelID: 102,
        HotelName: 'Madinah Hilton',
        RoomTypeID: 2,
        RoomTypeTitle: 'Triple Room',
        RoomCount: 3,
        StartDate: '2025-04-05',
        EndDate: '2025-04-10',
        NightsCount: 5,
        UnitCostPrice: 300,
        UnitOriginalPrice: 333,
        UnitSellingPrice: 366,
        UnitTax: 18.3,
        UnitPriceWithTax: 384.3,
        TotalCostPrice: 900,
        TotalOriginalPrice: 1000,
        TotalSellingPrice: 1100,
        TotalTax: 55,
        TotalPriceWithTax: 1155,
      },
    ],
    VisaVouchers: [],
    CateringVouchers: [],
    TripVouchers: [],
    TicketVouchers: [],
  },
  5005: {
    Voucher: MOCK_VOUCHERS[1003][0],
    HotelVouchers: [],
    VisaVouchers: [],
    CateringVouchers: [
      {
        RequestCateringVoucherDetailID: 1,
        RequestVoucherID: 5005,
        CateringID: 1,
        FoodTypeID: 2,
        Count: 15,
        FoodTypeTitle: 'Lunch',
        CateringTitle: 'Al-Baik Catering Services',
        UnitCostPrice: 26.6,
        UnitOriginalPrice: 32,
        UnitSellingPrice: 34.6,
        UnitTax: 1.73,
        UnitPriceWithTax: 36.4,
        TotalCostPrice: 400,
        TotalOriginalPrice: 480,
        TotalSellingPrice: 520,
        TotalTax: 26,
        TotalPriceWithTax: 546,
      },
    ],
    TripVouchers: [],
    TicketVouchers: [],
  },
  5006: {
    Voucher: MOCK_VOUCHERS[1005][0],
    HotelVouchers: [],
    VisaVouchers: [],
    CateringVouchers: [],
    TripVouchers: [],
    TicketVouchers: [
      {
        RequestTicketVoucherDetailID: 1,
        RequestVoucherID: 5006,
        TicketClass: 'Business',
        TripType: 'Round Trip',
        SourceCity: 'Cairo',
        SourceCountry: 'Egypt',
        DestCity: 'Jeddah',
        DestCountry: 'Saudi Arabia',
        TravelDate: '2025-01-10',
        Count: 25,
        AirlineName: 'Saudi Arabian Airlines',
        UnitCostPrice: 100,
        UnitOriginalPrice: 120,
        UnitSellingPrice: 132,
        UnitTax: 6.6,
        UnitPriceWithTax: 138.6,
        TotalCostPrice: 2500,
        TotalOriginalPrice: 3000,
        TotalSellingPrice: 3300,
        TotalTax: 165,
        TotalPriceWithTax: 3465,
      },
    ],
  },
  5007: {
    Voucher: MOCK_VOUCHERS[1005][1],
    HotelVouchers: [
      {
        RequestHotelVoucherDetailID: 3,
        RequestVoucherID: 5007,
        HotelID: 103,
        HotelName: 'Abraj Al-Bait Towers Hotel',
        RoomTypeID: 3,
        RoomTypeTitle: 'Suite',
        RoomCount: 5,
        StartDate: '2025-01-10',
        EndDate: '2025-01-20',
        NightsCount: 10,
        UnitCostPrice: 600,
        UnitOriginalPrice: 700,
        UnitSellingPrice: 760,
        UnitTax: 38,
        UnitPriceWithTax: 798,
        TotalCostPrice: 3000,
        TotalOriginalPrice: 3500,
        TotalSellingPrice: 3800,
        TotalTax: 190,
        TotalPriceWithTax: 3990,
      },
    ],
    VisaVouchers: [],
    CateringVouchers: [],
    TripVouchers: [],
    TicketVouchers: [],
  },
};

export const MOCK_VOUCHER_LOGS: Record<number, VoucherStatusLogModel[]> = {
  5001: [
    {
      RequestVoucherStatusLogID: 1,
      RequestVoucherID: 5001,
      VoucherStatusID: 1,
      Notes: 'Voucher created and submitted for review',
      CreatedAt: '2025-02-16T10:00:00',
      CreatedBy: 'Ahmed Al-Rashidi',
      StatusTitle: 'Pending',
    },
    {
      RequestVoucherStatusLogID: 2,
      RequestVoucherID: 5001,
      VoucherStatusID: 2,
      Notes: 'Under review by admin team',
      CreatedAt: '2025-02-17T14:30:00',
      CreatedBy: 'System Admin',
      StatusTitle: 'Pending Approval',
    },
  ],
  5002: [
    {
      RequestVoucherStatusLogID: 3,
      RequestVoucherID: 5002,
      VoucherStatusID: 1,
      Notes: 'Visa voucher submitted',
      CreatedAt: '2025-02-16T10:05:00',
      CreatedBy: 'Ahmed Al-Rashidi',
      StatusTitle: 'Pending',
    },
    {
      RequestVoucherStatusLogID: 4,
      RequestVoucherID: 5002,
      VoucherStatusID: 1,
      Notes: 'Approved after document verification',
      CreatedAt: '2025-02-20T09:00:00',
      CreatedBy: 'Visa Officer',
      StatusTitle: 'Approved',
    },
  ],
  5005: [
    {
      RequestVoucherStatusLogID: 5,
      RequestVoucherID: 5005,
      VoucherStatusID: 1,
      Notes: 'Catering voucher submitted',
      CreatedAt: '2025-04-02T08:30:00',
      CreatedBy: 'Ahmed Al-Rashidi',
      StatusTitle: 'Pending',
    },
    {
      RequestVoucherStatusLogID: 6,
      RequestVoucherID: 5005,
      VoucherStatusID: 10,
      Notes: 'Catering provider not available for this date range',
      CreatedAt: '2025-04-05T11:00:00',
      CreatedBy: 'Operations Manager',
      StatusTitle: 'Rejected',
    },
  ],
};
