import { DashboardRequestModel, DashboardVoucherDetailsModel } from './distributed-dashboard.model';

// Currently using local mock data for frontend prototype. Later this can be replaced with backend API.

export const MOCK_PACKAGE_REQUESTS: DashboardRequestModel[] = [
  {
    Id: 1042,
    StatusId: 3,
    StatusName: 'In Progress',
    AddedDate: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
    PassengerCount: 4,
    Title: 'umrah package makkah & madinah',
    Price: 12500,
  },
  {
    Id: 1039,
    StatusId: 1,
    StatusName: 'New',
    AddedDate: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000),
    PassengerCount: 2,
    Title: 'economy umrah madinah first',
    Price: 0,
  },
  {
    Id: 1036,
    StatusId: 2,
    StatusName: 'Confirmed',
    AddedDate: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000),
    PassengerCount: 6,
    Title: 'vip umrah package makkah',
    Price: 28750,
  },
  {
    Id: 1031,
    StatusId: 4,
    StatusName: 'Completed',
    AddedDate: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000),
    PassengerCount: 3,
    Title: 'ramadan umrah group package',
    Price: 18200,
  },
  {
    Id: 1028,
    StatusId: 5,
    StatusName: 'Pending',
    AddedDate: new Date(Date.now() - 3 * 60 * 60 * 1000),
    PassengerCount: 8,
    Title: 'family umrah makkah madinah combo',
    Price: 0,
  },
];

export const MOCK_VOUCHER_DETAILS: DashboardVoucherDetailsModel[] = [
  {
    Voucher: {
      RequestVoucherID: 501,
      RequestVoucherCode: 'QT-2025-0501',
      SeroPackageRequestID: 1042,
      RequestVoucherTypeID: 1,
      VoucherStatusForAdminID: 2,
      VoucherStatusForAgentID: 1,
      VoucherStatusForAdminTitle: 'Approved',
      VoucherStatusForAgentTitle: 'Accepted',
      TotalSellingPrice: 8500,
      TotalTax: 850,
      AddedDate: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000),
    },
  },
  {
    Voucher: {
      RequestVoucherID: 502,
      RequestVoucherCode: 'QT-2025-0502',
      SeroPackageRequestID: 1042,
      RequestVoucherTypeID: 2,
      VoucherStatusForAdminID: 1,
      VoucherStatusForAgentID: 1,
      VoucherStatusForAdminTitle: 'Pending',
      VoucherStatusForAgentTitle: 'Pending',
      TotalSellingPrice: 2200,
      TotalTax: 220,
      AddedDate: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
    },
  },
  {
    Voucher: {
      RequestVoucherID: 503,
      RequestVoucherCode: 'QT-2025-0503',
      SeroPackageRequestID: 1039,
      RequestVoucherTypeID: 3,
      VoucherStatusForAdminID: 2,
      VoucherStatusForAgentID: 2,
      VoucherStatusForAdminTitle: 'Approved',
      VoucherStatusForAgentTitle: 'Approved',
      TotalSellingPrice: 0,
      TotalTax: 0,
      AddedDate: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000),
    },
  },
  {
    Voucher: {
      RequestVoucherID: 504,
      RequestVoucherCode: 'QT-2025-0504',
      SeroPackageRequestID: 1036,
      RequestVoucherTypeID: 4,
      VoucherStatusForAdminID: 3,
      VoucherStatusForAgentID: 1,
      VoucherStatusForAdminTitle: 'In Review',
      VoucherStatusForAgentTitle: 'Pending',
      TotalSellingPrice: 3600,
      TotalTax: 360,
      AddedDate: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000),
    },
  },
  {
    Voucher: {
      RequestVoucherID: 505,
      RequestVoucherCode: 'QT-2025-0505',
      SeroPackageRequestID: 1031,
      RequestVoucherTypeID: 5,
      VoucherStatusForAdminID: 2,
      VoucherStatusForAgentID: 2,
      VoucherStatusForAdminTitle: 'Approved',
      VoucherStatusForAgentTitle: 'Approved',
      TotalSellingPrice: 5400,
      TotalTax: 540,
      AddedDate: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000),
    },
  },
];
