import { SeroPackageModel } from './packages.model';

// Currently using local mock data for frontend prototype. Later this can be replaced with backend API.

export const MOCK_PACKAGES: SeroPackageModel[] = [
  {
    PackageID: 1001,
    PackageCode: 'PKG-MKH-001',
    Title: 'Makkah & Madinah Premium Umrah Package',
    Price: 12500,
    StartDate: new Date('2025-03-01'),
    EndDate: new Date('2025-03-15'),
    IsVisaIncluded: true,
    VerifiedPrice: true,
    GuestCount: 2,
    Quantity: 15,
    ImageUrl: null,
    IsActive: true,
    Hotels: [
      {
        Id: 1, SeroPackageId: 1001, CityId: 1, CityName: 'Makkah',
        HotelId: 10, HotelName: 'Hilton Makkah Convention Hotel',
        HotelCategoryName: 'Luxury', RoomTypeName: 'Deluxe Double',
        DistrictName: 'Al-Misfalah', HotelStar: 5,
        NightsCount: 5, RoomCount: 1, DistanceFromHaram: 0.5,
      },
      {
        Id: 2, SeroPackageId: 1001, CityId: 2, CityName: 'Madinah',
        HotelId: 20, HotelName: 'Anwar Al Madinah Mövenpick',
        HotelCategoryName: 'Luxury', RoomTypeName: 'Deluxe Double',
        DistrictName: 'Central District', HotelStar: 5,
        NightsCount: 4, RoomCount: 1, DistanceFromHaram: 0.3,
      },
    ],
    HotelCounts: [
      { Id: 1, SeroPackageId: 1001, CityId: 1, CityName: 'Makkah', NightCount: 5 },
      { Id: 2, SeroPackageId: 1001, CityId: 2, CityName: 'Madinah', NightCount: 4 },
    ],
    Trips: [
      { Id: 1, SeroPackageId: 1001, TripPath: 'Jeddah Airport → Makkah', CarType: 'Bus', VehiclesCount: 1 },
      { Id: 2, SeroPackageId: 1001, TripPath: 'Makkah → Madinah', CarType: 'Minivan', VehiclesCount: 1 },
    ],
    Tickets: [
      {
        Id: 1, SeroPackageId: 1001,
        SourceCountryName: 'Egypt', SourceCityName: 'Cairo',
        DestinationCountryName: 'Saudi Arabia', DestinationCityName: 'Jeddah',
        AirlineCompanyNameEn: 'EgyptAir', SeatCount: 2,
        TripType: 'RoundTrip', TravelClass: 'Economy',
      },
    ],
    Caterings: [
      { Id: 1, SeroPackageId: 1001, CateringType: 'Breakfast', FoodType: 'Continental', Count: 9 },
      { Id: 2, SeroPackageId: 1001, CateringType: 'Dinner', FoodType: 'Arabic Buffet', Count: 9 },
    ],
    Tags: [
      { Id: 1, Name: 'VIP', Color: '#3a472a' },
      { Id: 2, Name: 'Visa Included', Color: '#16a34a' },
      { Id: 3, Name: 'Luxury', Color: '#8c7b3d' },
    ],
    Agents: [{ Id: 1, SeroPackageId: 1001, AgentId: 201, IsActive: true }],
  },
  {
    PackageID: 1002,
    PackageCode: 'PKG-ECO-002',
    Title: 'Economy Umrah — Madinah First',
    Price: 6800,
    StartDate: new Date('2025-04-10'),
    EndDate: new Date('2025-04-20'),
    IsVisaIncluded: false,
    VerifiedPrice: false,
    GuestCount: 4,
    Quantity: 30,
    ImageUrl: null,
    IsActive: true,
    Hotels: [
      {
        Id: 3, SeroPackageId: 1002, CityId: 2, CityName: 'Madinah',
        HotelId: 21, HotelName: 'Dar Al Iman Grand Hotel',
        HotelCategoryName: 'Standard', RoomTypeName: 'Triple Room',
        DistrictName: 'Central District', HotelStar: 3,
        NightsCount: 4, RoomCount: 2, DistanceFromHaram: 0.8,
      },
      {
        Id: 4, SeroPackageId: 1002, CityId: 1, CityName: 'Makkah',
        HotelId: null, HotelName: null,
        HotelCategoryName: 'Standard', RoomTypeName: 'Triple Room',
        DistrictName: 'Ajyad District', HotelStar: 3,
        NightsCount: 5, RoomCount: 2, DistanceFromHaram: 1.2,
      },
    ],
    HotelCounts: [
      { Id: 3, SeroPackageId: 1002, CityId: 2, CityName: 'Madinah', NightCount: 4 },
      { Id: 4, SeroPackageId: 1002, CityId: 1, CityName: 'Makkah', NightCount: 5 },
    ],
    Trips: [
      { Id: 3, SeroPackageId: 1002, TripPath: 'Jeddah Airport → Madinah', CarType: 'Bus', VehiclesCount: 1 },
    ],
    Tickets: [],
    Caterings: [
      { Id: 3, SeroPackageId: 1002, CateringType: 'Breakfast', FoodType: 'Continental', Count: 9 },
    ],
    Tags: [
      { Id: 4, Name: 'Economy', Color: '#6b7280' },
      { Id: 5, Name: 'Budget-Friendly', Color: '#2563eb' },
    ],
    Agents: [{ Id: 2, SeroPackageId: 1002, AgentId: 201, IsActive: true }],
  },
  {
    PackageID: 1003,
    PackageCode: 'PKG-VIP-003',
    Title: 'VIP Umrah Package — Full Board',
    Price: 28750,
    StartDate: new Date('2025-05-05'),
    EndDate: new Date('2025-05-19'),
    IsVisaIncluded: true,
    VerifiedPrice: true,
    GuestCount: 2,
    Quantity: 5,
    ImageUrl: null,
    IsActive: true,
    Hotels: [
      {
        Id: 5, SeroPackageId: 1003, CityId: 1, CityName: 'Makkah',
        HotelId: 11, HotelName: 'Fairmont Makkah Clock Royal Tower',
        HotelCategoryName: 'Ultra Luxury', RoomTypeName: 'Suite',
        DistrictName: 'Al-Haram Area', HotelStar: 5,
        NightsCount: 7, RoomCount: 1, DistanceFromHaram: 0.1,
      },
      {
        Id: 6, SeroPackageId: 1003, CityId: 2, CityName: 'Madinah',
        HotelId: 22, HotelName: 'Oberoi Al Madina',
        HotelCategoryName: 'Ultra Luxury', RoomTypeName: 'Suite',
        DistrictName: 'Al-Masjid an-Nabawi Area', HotelStar: 5,
        NightsCount: 5, RoomCount: 1, DistanceFromHaram: 0.1,
      },
    ],
    HotelCounts: [
      { Id: 5, SeroPackageId: 1003, CityId: 1, CityName: 'Makkah', NightCount: 7 },
      { Id: 6, SeroPackageId: 1003, CityId: 2, CityName: 'Madinah', NightCount: 5 },
    ],
    Trips: [
      { Id: 4, SeroPackageId: 1003, TripPath: 'Jeddah Airport → Makkah', CarType: 'Private Car', VehiclesCount: 1 },
      { Id: 5, SeroPackageId: 1003, TripPath: 'Makkah → Madinah', CarType: 'Private Car', VehiclesCount: 1 },
      { Id: 6, SeroPackageId: 1003, TripPath: 'Madinah → Jeddah Airport', CarType: 'Private Car', VehiclesCount: 1 },
    ],
    Tickets: [
      {
        Id: 2, SeroPackageId: 1003,
        SourceCountryName: 'UAE', SourceCityName: 'Dubai',
        DestinationCountryName: 'Saudi Arabia', DestinationCityName: 'Jeddah',
        AirlineCompanyNameEn: 'Emirates', SeatCount: 2,
        TripType: 'RoundTrip', TravelClass: 'Business',
      },
    ],
    Caterings: [
      { Id: 4, SeroPackageId: 1003, CateringType: 'Breakfast', FoodType: 'Full English', Count: 14 },
      { Id: 5, SeroPackageId: 1003, CateringType: 'Lunch', FoodType: 'International Buffet', Count: 14 },
      { Id: 6, SeroPackageId: 1003, CateringType: 'Dinner', FoodType: 'Gourmet Arabic', Count: 14 },
    ],
    Tags: [
      { Id: 6, Name: 'VIP', Color: '#3a472a' },
      { Id: 7, Name: 'Full Board', Color: '#8c7b3d' },
      { Id: 8, Name: 'Visa Included', Color: '#16a34a' },
      { Id: 9, Name: 'Business Class', Color: '#7c3aed' },
    ],
    Agents: [{ Id: 3, SeroPackageId: 1003, AgentId: 201, IsActive: true }],
  },
  {
    PackageID: 1004,
    PackageCode: 'PKG-RAM-004',
    Title: 'Ramadan Umrah Group Package',
    Price: 18200,
    StartDate: new Date('2025-03-28'),
    EndDate: new Date('2025-04-08'),
    IsVisaIncluded: true,
    VerifiedPrice: false,
    GuestCount: 6,
    Quantity: 8,
    ImageUrl: null,
    IsActive: true,
    Hotels: [
      {
        Id: 7, SeroPackageId: 1004, CityId: 1, CityName: 'Makkah',
        HotelId: 12, HotelName: 'Swissôtel Al Maqam',
        HotelCategoryName: 'Premium', RoomTypeName: 'Quadruple Room',
        DistrictName: 'Al-Haram Area', HotelStar: 5,
        NightsCount: 6, RoomCount: 2, DistanceFromHaram: 0.2,
      },
    ],
    HotelCounts: [
      { Id: 7, SeroPackageId: 1004, CityId: 1, CityName: 'Makkah', NightCount: 6 },
    ],
    Trips: [
      { Id: 7, SeroPackageId: 1004, TripPath: 'Jeddah Airport → Makkah', CarType: 'Bus', VehiclesCount: 1 },
    ],
    Tickets: [
      {
        Id: 3, SeroPackageId: 1004,
        SourceCountryName: 'Turkey', SourceCityName: 'Istanbul',
        DestinationCountryName: 'Saudi Arabia', DestinationCityName: 'Jeddah',
        AirlineCompanyNameEn: 'Turkish Airlines', SeatCount: 6,
        TripType: 'RoundTrip', TravelClass: 'Economy',
      },
    ],
    Caterings: [
      { Id: 7, SeroPackageId: 1004, CateringType: 'Iftar', FoodType: 'Arabic Buffet', Count: 6 },
      { Id: 8, SeroPackageId: 1004, CateringType: 'Suhoor', FoodType: 'Traditional', Count: 6 },
    ],
    Tags: [
      { Id: 10, Name: 'Ramadan Special', Color: '#d97706' },
      { Id: 11, Name: 'Group', Color: '#2563eb' },
      { Id: 12, Name: 'Visa Included', Color: '#16a34a' },
    ],
    Agents: [{ Id: 4, SeroPackageId: 1004, AgentId: 202, IsActive: true }],
  },
  {
    PackageID: 1005,
    PackageCode: 'PKG-FAM-005',
    Title: 'Family Umrah — Makkah & Madinah Combo',
    Price: 0,
    StartDate: new Date('2025-06-01'),
    EndDate: new Date('2025-06-14'),
    IsVisaIncluded: false,
    VerifiedPrice: false,
    GuestCount: 5,
    Quantity: 10,
    ImageUrl: null,
    IsActive: true,
    Hotels: [
      {
        Id: 8, SeroPackageId: 1005, CityId: 1, CityName: 'Makkah',
        HotelId: 13, HotelName: 'Sheraton Makkah Jabal Al Kaaba',
        HotelCategoryName: 'Premium', RoomTypeName: 'Family Suite',
        DistrictName: 'Jabal Al Kaaba', HotelStar: 5,
        NightsCount: 7, RoomCount: 1, DistanceFromHaram: 0.6,
      },
      {
        Id: 9, SeroPackageId: 1005, CityId: 2, CityName: 'Madinah',
        HotelId: 23, HotelName: 'Dar Al Iman Grand Hotel',
        HotelCategoryName: 'Premium', RoomTypeName: 'Family Suite',
        DistrictName: 'Central District', HotelStar: 4,
        NightsCount: 5, RoomCount: 1, DistanceFromHaram: 0.7,
      },
    ],
    HotelCounts: [
      { Id: 8, SeroPackageId: 1005, CityId: 1, CityName: 'Makkah', NightCount: 7 },
      { Id: 9, SeroPackageId: 1005, CityId: 2, CityName: 'Madinah', NightCount: 5 },
    ],
    Trips: [
      { Id: 8, SeroPackageId: 1005, TripPath: 'Jeddah Airport → Makkah', CarType: 'Minivan', VehiclesCount: 1 },
      { Id: 9, SeroPackageId: 1005, TripPath: 'Makkah → Madinah', CarType: 'Minivan', VehiclesCount: 1 },
    ],
    Tickets: [],
    Caterings: [
      { Id: 9, SeroPackageId: 1005, CateringType: 'Breakfast', FoodType: 'Continental', Count: 12 },
    ],
    Tags: [
      { Id: 13, Name: 'Family', Color: '#8b5cf6' },
      { Id: 14, Name: 'Estimating', Color: '#6b7280' },
    ],
    Agents: [{ Id: 5, SeroPackageId: 1005, AgentId: 202, IsActive: true }],
  },
  {
    PackageID: 1006,
    PackageCode: 'PKG-GRP-006',
    Title: 'Budget Group Umrah — 10 Nights',
    Price: 8900,
    StartDate: new Date('2025-07-15'),
    EndDate: new Date('2025-07-25'),
    IsVisaIncluded: false,
    VerifiedPrice: true,
    GuestCount: 3,
    Quantity: 20,
    ImageUrl: null,
    IsActive: true,
    Hotels: [
      {
        Id: 10, SeroPackageId: 1006, CityId: 1, CityName: 'Makkah',
        HotelId: null, HotelName: null,
        HotelCategoryName: 'Economy', RoomTypeName: 'Triple Room',
        DistrictName: 'Al-Misfalah', HotelStar: 3,
        NightsCount: 6, RoomCount: 1, DistanceFromHaram: 2.0,
      },
      {
        Id: 11, SeroPackageId: 1006, CityId: 2, CityName: 'Madinah',
        HotelId: null, HotelName: null,
        HotelCategoryName: 'Economy', RoomTypeName: 'Triple Room',
        DistrictName: 'Central District', HotelStar: 3,
        NightsCount: 4, RoomCount: 1, DistanceFromHaram: 1.5,
      },
    ],
    HotelCounts: [
      { Id: 10, SeroPackageId: 1006, CityId: 1, CityName: 'Makkah', NightCount: 6 },
      { Id: 11, SeroPackageId: 1006, CityId: 2, CityName: 'Madinah', NightCount: 4 },
    ],
    Trips: [
      { Id: 10, SeroPackageId: 1006, TripPath: 'Jeddah Airport → Makkah', CarType: 'Bus', VehiclesCount: 1 },
      { Id: 11, SeroPackageId: 1006, TripPath: 'Makkah → Madinah', CarType: 'Bus', VehiclesCount: 1 },
    ],
    Tickets: [],
    Caterings: [],
    Tags: [
      { Id: 15, Name: 'Budget', Color: '#0891b2' },
      { Id: 16, Name: 'Group', Color: '#2563eb' },
    ],
    Agents: [{ Id: 6, SeroPackageId: 1006, AgentId: 203, IsActive: true }],
  },
];

export const MOCK_MY_PACKAGES: SeroPackageModel[] = MOCK_PACKAGES.slice(0, 3).map(p => ({
  ...p,
  PackageCode: 'MY-' + p.PackageCode,
  PackageID: (p.PackageID ?? 0) + 1000,
  OwnerID: 201,
}));
