/**
 * Sidebar Navigation Configuration
 * Configuration file for the sidebar menu structure
 * 
 * This file defines the complete navigation structure for the hotel/property management system.
 * Menu items support multi-level nesting and route configuration.
 */

import { NavItem } from './nav-item/nav-item';

export const SIDEBAR_CONFIG: NavItem[] = [
  {
    displayName: 'لوحة التحكم',
    displayNameEn: 'Dashboard',
    iconName: 'layout-dashboard',
    route: 'Dashboard',
    displayOrder: 1,
    isChild: false,
    authActions: [],
  },
  {
    displayName: 'الاستقبال',
    displayNameEn: 'Front Desk',
    iconName: 'building-store',
    displayOrder: 2,
    isChild: false,
    authActions: [],
    children: [
      {
        displayName: 'انشاء حجز',
        displayNameEn: 'Create Booking',
        iconName: 'list',
        route: 'bookings',
        displayOrder: 1,
        isChild: true,
        authActions: [],
      },
      {
        displayName: 'الوصول',
        displayNameEn: 'Arrival',
        iconName: 'login',
        route: 'reception-arrivals',
        displayOrder: 2,
        isChild: true,
        authActions: [],
      },
      {
        displayName: 'المغادرة',
        displayNameEn: 'Departure',
        iconName: 'logout',
        route: 'reception-departures',
        displayOrder: 3,
        isChild: true,
        authActions: [],
      },
      {
        displayName: 'حجز مندوب',
        displayNameEn: 'Delegate Booking',
        iconName: 'user-shield',
        route: 'delegate-booking',
        displayOrder: 4,
        isChild: true,
        authActions: [],
      },
    ],
  },
  {
    displayName: 'حجز فاضي مليان',
    displayNameEn: 'Empty-Full Booking',
    iconName: 'container',
    route: 'empty-full-booking',
    displayOrder: 3.25,
    isChild: false,
    authActions: [],
  },
  {
    displayName: 'حجز فاضي مليان 2',
    displayNameEn: 'Empty-Full Booking 2',
    iconName: 'container',
    route: 'empty-full-booking-2',
    displayOrder: 3.26,
    isChild: false,
    authActions: [],
  },
  {
    displayName: 'الحجوزات المغلقة',
    displayNameEn: 'Closed Bookings',
    iconName: 'archive',
    route: 'packaged-bookings',
    displayOrder: 3.5,
    isChild: false,
    authActions: [],
  },
  {
    displayName: 'الوحدات السكنية',
    displayNameEn: 'Residential Units',
    iconName: 'building',
    displayOrder: 4,
    isChild: false,
    authActions: [],
    children: [
      {
        displayName: 'الغرف والطوابق',
        displayNameEn: 'Rooms & Floors',
        iconName: 'door',
        route: 'rooms-floors',
        displayOrder: 1,
        isChild: true,
        authActions: [],
      },
      {
        displayName: 'تقرير حالة الغرف',
        displayNameEn: 'Room Status Report',
        iconName: 'calendar-week',
        route: 'room-status-report',
        displayOrder: 2,
        isChild: true,
        authActions: [],
      },
      {
        displayName: 'المصادر',
        displayNameEn: 'Sources',
        iconName: 'world',
        route: 'channels',
        displayOrder: 3,
        isChild: true,
        authActions: [],
      },
    ],
  },
  {
    displayName: 'النزلاء والجهات',
    displayNameEn: 'Guests & Entities',
    iconName: 'users',
    displayOrder: 5,
    isChild: false,
    authActions: [],
    children: [
      {
        displayName: 'إدارة النزلاء',
        displayNameEn: 'Guest Management',
        iconName: 'user',
        route: 'guests',
        displayOrder: 1,
        isChild: true,
        authActions: [],
      },
      {
        displayName: 'إدارة الجهات',
        displayNameEn: 'Entity Management',
        iconName: 'building-community',
        route: 'entities',
        displayOrder: 2,
        isChild: true,
        authActions: [],
      },
    ],
  },
  {
    displayName: 'المالية',
    displayNameEn: 'Finance',
    iconName: 'currency-dollar',
    displayOrder: 6,
    isChild: false,
    authActions: [],
    children: [
      {
        displayName: 'كشف الحساب',
        displayNameEn: 'Account Statement',
        iconName: 'file-text',
        route: 'account-statement',
        displayOrder: 1,
        isChild: true,
        authActions: [],
      },
      {
        displayName: 'ميزان المراجعة',
        displayNameEn: 'Trial Balance',
        iconName: 'scale',
        route: 'trial-balance',
        displayOrder: 2,
        isChild: true,
        authActions: [],
      },
      {
        displayName: 'مراكز التكلفة',
        displayNameEn: 'Cost Centers',
        iconName: 'building-store',
        route: 'cost-centers',
        displayOrder: 3,
        isChild: true,
        authActions: [],
      },
      {
        displayName: 'الشجرة المحاسبية',
        displayNameEn: 'Chart of Accounts',
        iconName: 'hierarchy',
        route: 'chart-of-accounts',
        displayOrder: 4,
        isChild: true,
        authActions: [],
      },
      {
        displayName: 'قائمة الدخل',
        displayNameEn: 'Income Statement',
        iconName: 'chart-line',
        route: 'income-statement',
        displayOrder: 5,
        isChild: true,
        authActions: [],
      },
      {
        displayName: 'الرصيد الافتتاحي',
        displayNameEn: 'Opening Balance',
        iconName: 'coin',
        route: 'opening-balance',
        displayOrder: 6,
        isChild: true,
        authActions: [],
      },
      {
        displayName: 'القيود',
        displayNameEn: 'Journal Entries',
        iconName: 'file-invoice',
        route: 'journal-entries',
        displayOrder: 7,
        isChild: true,
        authActions: [],
      },
      {
        displayName: 'السنة المالية',
        displayNameEn: 'Fiscal Year',
        iconName: 'calendar-time',
        route: 'fiscal-year',
        displayOrder: 8,
        isChild: true,
        authActions: [],
      },
      {
        displayName: 'التقارير المالية',
        displayNameEn: 'Financial Reports',
        iconName: 'report-analytics',
        route: 'financial-reports',
        displayOrder: 9,
        isChild: true,
        authActions: [],
      },
      {
        displayName: 'توجيه الحسابات',
        displayNameEn: 'Account Routing',
        iconName: 'route',
        route: 'account-routing',
        displayOrder: 10,
        isChild: true,
        authActions: [],
      },
    ],
  },
  {
    displayName: 'الموردون والمشتريات',
    displayNameEn: 'Suppliers & Procurement',
    iconName: 'truck',
    displayOrder: 7,
    isChild: false,
    authActions: [],
    children: [
      {
        displayName: 'الموردون',
        displayNameEn: 'Suppliers',
        iconName: 'truck-delivery',
        route: 'suppliers',
        displayOrder: 2,
        isChild: true,
        authActions: [],
      },
      {
        displayName: 'المصروفات',
        displayNameEn: 'Expenses',
        iconName: 'credit-card',
        route: 'expenses',
        displayOrder: 3,
        isChild: true,
        authActions: [],
      },
      {
        displayName: 'البنوك',
        displayNameEn: 'Banks',
        iconName: 'building-bank',
        route: 'banks',
        displayOrder: 4,
        isChild: true,
        authActions: [],
      },
    ],
  },
  {
    displayName: 'التسعير والخدمات',
    displayNameEn: 'Pricing & Services',
    iconName: 'tag',
    displayOrder: 8,
    isChild: false,
    authActions: [],
    children: [
      {
        displayName: 'إدارة الأسعار',
        displayNameEn: 'Price Management',
        iconName: 'currency-dollar',
        route: 'pricing',
        displayOrder: 1,
        isChild: true,
        authActions: [],
      },
      {
        displayName: 'الأوقات الذروة',
        displayNameEn: 'Peak Times',
        iconName: 'chart-line',
        route: 'reports',
        queryParams: { category: 'peak-times' },
        displayOrder: 2,
        isChild: true,
        authActions: [],
      },
      {
        displayName: 'الضرائب والرسوم',
        displayNameEn: 'Taxes & Fees',
        iconName: 'receipt-tax',
        route: 'taxes-fees',
        displayOrder: 3,
        isChild: true,
        authActions: [],
      },
      {
        displayName: 'العناصر والخدمات',
        displayNameEn: 'Items & Services',
        iconName: 'package',
        route: 'items-services',
        displayOrder: 4,
        isChild: true,
        authActions: [],
      },
    ],
  },
  {
    displayName: 'العلاقات والإشعارات',
    displayNameEn: 'Relations & Notifications',
    iconName: 'bell',
    displayOrder: 9,
    isChild: false,
    authActions: [],
    children: [
      {
        displayName: 'الوكلاء',
        displayNameEn: 'Agents',
        iconName: 'user-check',
        route: 'agents',
        displayOrder: 1,
        isChild: true,
        authActions: [],
      },
      {
        displayName: 'النزلاء',
        displayNameEn: 'Guests',
        iconName: 'users-group',
        route: 'guests-relations',
        displayOrder: 2,
        isChild: true,
        authActions: [],
      },
      {
        displayName: 'الرسائل',
        displayNameEn: 'Messaging',
        iconName: 'message',
        route: 'messaging',
        displayOrder: 3,
        isChild: true,
        authActions: [],
      },
    ],
  },
  {
    displayName: 'التقارير',
    displayNameEn: 'Reports',
    iconName: 'report-analytics',
    route: 'reports',
    displayOrder: 10,
    isChild: false,
    authActions: [],
  },
  {
    displayName: 'الإعدادات',
    displayNameEn: 'Settings',
    iconName: 'settings',
    displayOrder: 11,
    isChild: false,
    authActions: [],
    children: [
      {
        displayName: 'التكاملات',
        displayNameEn: 'Integrations',
        iconName: 'plug',
        route: 'integrations',
        displayOrder: 3,
        isChild: true,
        authActions: [],
      },
      {
        displayName: 'الفندق',
        displayNameEn: 'Hotel',
        iconName: 'building',
        displayOrder: 4,
        isChild: true,
        authActions: [],
        children: [
          {
            displayName: 'معلومات الفندق',
            displayNameEn: 'Hotel Information',
            iconName: 'info-circle',
            route: 'hotelInfo',
            displayOrder: 1,
            isChild: true,
            authActions: [],
          },
        ],
      },
    ],
  },
];

/**
 * Storage keys for sidebar state persistence
 */
export const SIDEBAR_STORAGE_KEYS = {
  COLLAPSED: 'sidebar_collapsed',
  EXPANDED_SECTIONS: 'sidebar_expanded_sections',
} as const;
