// Currently using local mock data for frontend prototype. Later this can be replaced with backend API.
import { RequestVoucherModel } from '../orders/orders.model';

export const MOCK_ALL_VOUCHERS: RequestVoucherModel[] = [
  {
    RequestVoucherID: 5001,
    RequestVoucherCode: 'VCH-5001',
    SeroPackageRequestID: 1001,
    RequestVoucherTypeID: 1,
    VoucherStatusForAgentID: 1,
    VoucherStatusForAdminID: 2,
    VoucherStatusForAgentTitle: 'Confirmed',
    VoucherStatusForAdminTitle: 'Pending Approval',
    TotalCostPrice: 1800,
    TotalOriginalPrice: 2000,
    TotalSellingPrice: 2200,
    TotalTax: 110,
    TotalPriceWithTax: 2310,
    AddedDate: '2025-02-16T10:00:00',
    AgentID: 10,
  },
  {
    RequestVoucherID: 5002,
    RequestVoucherCode: 'VCH-5002',
    SeroPackageRequestID: 1001,
    RequestVoucherTypeID: 3,
    VoucherStatusForAgentID: 1,
    VoucherStatusForAdminID: 1,
    VoucherStatusForAgentTitle: 'Confirmed',
    VoucherStatusForAdminTitle: 'Approved',
    TotalCostPrice: 500,
    TotalOriginalPrice: 600,
    TotalSellingPrice: 650,
    TotalTax: 32,
    TotalPriceWithTax: 682,
    AddedDate: '2025-02-16T10:05:00',
    AgentID: 10,
  },
  {
    RequestVoucherID: 5003,
    RequestVoucherCode: 'VCH-5003',
    SeroPackageRequestID: 1001,
    RequestVoucherTypeID: 2,
    VoucherStatusForAgentID: 1,
    VoucherStatusForAdminID: 1,
    VoucherStatusForAgentTitle: 'Confirmed',
    VoucherStatusForAdminTitle: 'Approved',
    TotalCostPrice: 900,
    TotalOriginalPrice: 1000,
    TotalSellingPrice: 1100,
    TotalTax: 55,
    TotalPriceWithTax: 1155,
    AddedDate: '2025-02-16T10:10:00',
    AgentID: 10,
  },
  {
    RequestVoucherID: 5004,
    RequestVoucherCode: 'VCH-5004',
    SeroPackageRequestID: 1002,
    RequestVoucherTypeID: 1,
    VoucherStatusForAgentID: 2,
    VoucherStatusForAdminID: 2,
    VoucherStatusForAgentTitle: 'Pending',
    VoucherStatusForAdminTitle: 'Pending Approval',
    TotalCostPrice: 900,
    TotalOriginalPrice: 1000,
    TotalSellingPrice: 1100,
    TotalTax: 55,
    TotalPriceWithTax: 1155,
    AddedDate: '2025-03-02T09:00:00',
    AgentID: 10,
  },
  {
    RequestVoucherID: 5005,
    RequestVoucherCode: 'VCH-5005',
    SeroPackageRequestID: 1003,
    RequestVoucherTypeID: 4,
    VoucherStatusForAgentID: 3,
    VoucherStatusForAdminID: 10,
    VoucherStatusForAgentTitle: 'Rejected',
    VoucherStatusForAdminTitle: 'Rejected',
    TotalCostPrice: 400,
    TotalOriginalPrice: 480,
    TotalSellingPrice: 520,
    TotalTax: 26,
    TotalPriceWithTax: 546,
    AddedDate: '2025-04-02T08:30:00',
    AgentID: 10,
  },
  {
    RequestVoucherID: 5006,
    RequestVoucherCode: 'VCH-5006',
    SeroPackageRequestID: 1005,
    RequestVoucherTypeID: 5,
    VoucherStatusForAgentID: 1,
    VoucherStatusForAdminID: 1,
    VoucherStatusForAgentTitle: 'Confirmed',
    VoucherStatusForAdminTitle: 'Approved',
    TotalCostPrice: 2500,
    TotalOriginalPrice: 3000,
    TotalSellingPrice: 3300,
    TotalTax: 165,
    TotalPriceWithTax: 3465,
    AddedDate: '2024-12-02T10:00:00',
    AgentID: 10,
  },
  {
    RequestVoucherID: 5007,
    RequestVoucherCode: 'VCH-5007',
    SeroPackageRequestID: 1005,
    RequestVoucherTypeID: 1,
    VoucherStatusForAgentID: 1,
    VoucherStatusForAdminID: 1,
    VoucherStatusForAgentTitle: 'Confirmed',
    VoucherStatusForAdminTitle: 'Approved',
    TotalCostPrice: 3000,
    TotalOriginalPrice: 3500,
    TotalSellingPrice: 3800,
    TotalTax: 190,
    TotalPriceWithTax: 3990,
    AddedDate: '2024-12-02T10:15:00',
    AgentID: 10,
  },
  {
    RequestVoucherID: 5008,
    RequestVoucherCode: 'VCH-5008',
    SeroPackageRequestID: 1004,
    RequestVoucherTypeID: 3,
    VoucherStatusForAgentID: 2,
    VoucherStatusForAdminID: 2,
    VoucherStatusForAgentTitle: 'Pending',
    VoucherStatusForAdminTitle: 'Pending Approval',
    TotalCostPrice: 350,
    TotalOriginalPrice: 420,
    TotalSellingPrice: 460,
    TotalTax: 23,
    TotalPriceWithTax: 483,
    AddedDate: '2025-05-21T08:00:00',
    AgentID: 10,
  },
  {
    RequestVoucherID: 5009,
    RequestVoucherCode: 'VCH-5009',
    SeroPackageRequestID: 1004,
    RequestVoucherTypeID: 2,
    VoucherStatusForAgentID: 2,
    VoucherStatusForAdminID: 2,
    VoucherStatusForAgentTitle: 'Pending',
    VoucherStatusForAdminTitle: 'Pending Approval',
    TotalCostPrice: 700,
    TotalOriginalPrice: 800,
    TotalSellingPrice: 880,
    TotalTax: 44,
    TotalPriceWithTax: 924,
    AddedDate: '2025-05-21T08:05:00',
    AgentID: 10,
  },
  {
    RequestVoucherID: 5010,
    RequestVoucherCode: 'VCH-5010',
    SeroPackageRequestID: 1003,
    RequestVoucherTypeID: 1,
    VoucherStatusForAgentID: 3,
    VoucherStatusForAdminID: 10,
    VoucherStatusForAgentTitle: 'Rejected',
    VoucherStatusForAdminTitle: 'Rejected',
    TotalCostPrice: 1200,
    TotalOriginalPrice: 1400,
    TotalSellingPrice: 1540,
    TotalTax: 77,
    TotalPriceWithTax: 1617,
    AddedDate: '2025-04-02T09:00:00',
    AgentID: 10,
  },
];
