// Currently using local mock data for frontend prototype. Later this can be replaced with backend API.
import { AgentModel, UserAccountViewModel, CountryData, CityData } from './subagents.model';

export const MOCK_SUBAGENTS: AgentModel[] = [
  {
    AgentID: 101,
    AgentCode: 'SUB-001',
    AgentName: 'Al-Noor Travel Agency',
    AgentEmail: 'info@alnoor.sa',
    CountryID: 1,
    CountryName: 'Saudi Arabia',
    CityID: 1,
    CityName: 'Riyadh',
    CR_NO: '1010123456',
    Address: '123 King Fahd Road, Riyadh',
    Description: 'Leading travel agency in Riyadh specializing in Umrah packages.',
    IsActive: true,
    MasterAgentID: 10,
    LogoImageLocation: '',
  },
  {
    AgentID: 102,
    AgentCode: 'SUB-002',
    AgentName: 'Makkah Tours & Travel',
    AgentEmail: 'contact@makkah-tours.com',
    CountryID: 1,
    CountryName: 'Saudi Arabia',
    CityID: 2,
    CityName: 'Makkah',
    CR_NO: '1020234567',
    Address: 'Al-Masjid Al-Haram Area, Makkah',
    Description: '',
    IsActive: true,
    MasterAgentID: 10,
    LogoImageLocation: '',
  },
  {
    AgentID: 103,
    AgentCode: 'SUB-003',
    AgentName: 'Cairo Umrah Center',
    AgentEmail: 'admin@cairo-umrah.eg',
    CountryID: 2,
    CountryName: 'Egypt',
    CityID: 3,
    CityName: 'Cairo',
    CR_NO: '',
    Address: '45 Tahrir Square, Cairo',
    Description: 'Serving Egyptian pilgrims since 2005.',
    IsActive: true,
    MasterAgentID: 10,
    LogoImageLocation: '',
  },
  {
    AgentID: 104,
    AgentCode: 'SUB-004',
    AgentName: 'Istanbul Haj Services',
    AgentEmail: 'haj@istanbul-haj.tr',
    CountryID: 3,
    CountryName: 'Turkey',
    CityID: 4,
    CityName: 'Istanbul',
    CR_NO: 'TR123456',
    Address: '78 Sultanahmet District, Istanbul',
    Description: '',
    IsActive: false,
    MasterAgentID: 10,
    LogoImageLocation: '',
  },
  {
    AgentID: 105,
    AgentCode: 'SUB-005',
    AgentName: 'Madinah Hospitality Group',
    AgentEmail: 'info@madinah-hospitality.sa',
    CountryID: 1,
    CountryName: 'Saudi Arabia',
    CityID: 5,
    CityName: 'Madinah',
    CR_NO: '1030345678',
    Address: 'Near Al-Masjid Al-Nabawi, Madinah',
    Description: 'Premium hospitality for pilgrims in Madinah.',
    IsActive: true,
    MasterAgentID: 10,
    LogoImageLocation: '',
  },
];

export const MOCK_SUBAGENT_USERS: Record<number, UserAccountViewModel[]> = {
  101: [
    {
      UserID: 201,
      UserName: 'ahmed.alnoor',
      FirstName: 'Ahmed',
      LastName: 'Al-Rashidi',
      Email: 'ahmed@alnoor.sa',
      PhoneNumber: '+966501234567',
      IsActive: true,
      UserOwnerID: 101,
      UserTypeID: 2,
      AddedDate: '2024-01-15T10:00:00',
      LastUpdatedDate: '2024-06-20T14:30:00',
      AddedBy: 'Admin',
    },
    {
      UserID: 202,
      UserName: 'fatima.alnoor',
      FirstName: 'Fatima',
      LastName: 'Hassan',
      Email: 'fatima@alnoor.sa',
      PhoneNumber: '+966502345678',
      IsActive: true,
      UserOwnerID: 101,
      UserTypeID: 2,
      AddedDate: '2024-02-10T09:00:00',
      LastUpdatedDate: '2024-06-15T11:00:00',
      AddedBy: 'Ahmed Al-Rashidi',
    },
  ],
  102: [
    {
      UserID: 203,
      UserName: 'khalid.makkah',
      FirstName: 'Khalid',
      LastName: 'Al-Harbi',
      Email: 'khalid@makkah-tours.com',
      PhoneNumber: '+966503456789',
      IsActive: true,
      UserOwnerID: 102,
      UserTypeID: 2,
      AddedDate: '2024-03-05T08:00:00',
      LastUpdatedDate: '2024-07-01T10:00:00',
      AddedBy: 'Admin',
    },
  ],
  103: [
    {
      UserID: 204,
      UserName: 'omar.cairo',
      FirstName: 'Omar',
      LastName: 'Ibrahim',
      Email: 'omar@cairo-umrah.eg',
      PhoneNumber: '+201012345678',
      IsActive: false,
      UserOwnerID: 103,
      UserTypeID: 2,
      AddedDate: '2024-01-20T12:00:00',
      LastUpdatedDate: '2024-05-10T09:30:00',
      AddedBy: 'Admin',
    },
  ],
  104: [],
  105: [
    {
      UserID: 205,
      UserName: 'ali.madinah',
      FirstName: 'Ali',
      LastName: 'Al-Zaidi',
      Email: 'ali@madinah-hospitality.sa',
      PhoneNumber: '+966504567890',
      IsActive: true,
      UserOwnerID: 105,
      UserTypeID: 2,
      AddedDate: '2024-04-12T07:00:00',
      LastUpdatedDate: '2024-06-30T13:00:00',
      AddedBy: 'Admin',
    },
  ],
};

export const MOCK_COUNTRIES: CountryData[] = [
  { CountryID: 1, Title: 'المملكة العربية السعودية', TitleEnglish: 'Saudi Arabia' },
  { CountryID: 2, Title: 'مصر', TitleEnglish: 'Egypt' },
  { CountryID: 3, Title: 'تركيا', TitleEnglish: 'Turkey' },
  { CountryID: 4, Title: 'الأردن', TitleEnglish: 'Jordan' },
  { CountryID: 5, Title: 'الإمارات', TitleEnglish: 'UAE' },
  { CountryID: 6, Title: 'الكويت', TitleEnglish: 'Kuwait' },
  { CountryID: 7, Title: 'باكستان', TitleEnglish: 'Pakistan' },
  { CountryID: 8, Title: 'إندونيسيا', TitleEnglish: 'Indonesia' },
];

export const MOCK_CITIES: Record<number, CityData[]> = {
  1: [
    { CityID: 1, Name: 'الرياض', NameEn: 'Riyadh', CountryID: 1 },
    { CityID: 2, Name: 'مكة المكرمة', NameEn: 'Makkah', CountryID: 1 },
    { CityID: 5, Name: 'المدينة المنورة', NameEn: 'Madinah', CountryID: 1 },
    { CityID: 6, Name: 'جدة', NameEn: 'Jeddah', CountryID: 1 },
    { CityID: 7, Name: 'الدمام', NameEn: 'Dammam', CountryID: 1 },
  ],
  2: [
    { CityID: 3, Name: 'القاهرة', NameEn: 'Cairo', CountryID: 2 },
    { CityID: 8, Name: 'الإسكندرية', NameEn: 'Alexandria', CountryID: 2 },
  ],
  3: [
    { CityID: 4, Name: 'إسطنبول', NameEn: 'Istanbul', CountryID: 3 },
    { CityID: 9, Name: 'أنقرة', NameEn: 'Ankara', CountryID: 3 },
  ],
  4: [
    { CityID: 10, Name: 'عمّان', NameEn: 'Amman', CountryID: 4 },
  ],
  5: [
    { CityID: 11, Name: 'دبي', NameEn: 'Dubai', CountryID: 5 },
    { CityID: 12, Name: 'أبوظبي', NameEn: 'Abu Dhabi', CountryID: 5 },
  ],
};
